### ISSUE TITLE
LaTeX support.

### ISSUE THREAD

**Issue by chyyran** [fabiospampinato/notable#1]
Support LaTeX math typesetting, perhaps through the [KaTeX](https://katex.org/) library.

Examples of Electron-based Markdown Editors using KaTeX

* [Boostnote](https://boostnote.io/)
* [Markdown+Math (Visual Studio Code plugin)](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath)

**Comment by fabiospampinato** [comment]
It seems there's an extension for [showdown](https://github.com/showdownjs/showdown) (the markdown renderer we are using) already: https://github.com/obedm503/showdown-katex

Support for this should be easy, thanks for the suggestion!

**Comment by mjedmonds** [comment]
Would also love to see this!

**Comment by umgupta** [comment]
Hi! I tried to implement this. However, `showdown-katex` as published on npm registry is old (0.0.5) and doesn't work. 

I think (haven't tested) the newer version on the github repo works and can be used. Do you have any policy on how to "copy" this repo into the code as it can't be put into node-modules?

I can also just look at the code and copy the relevant code as an extension. 

LMK

**Comment by fabiospampinato** [comment]
@umgupta Actually you can install packages with NPM from a git repo, look [here](https://github.com/fabiospampinato/notable/blob/master/package.json/#L183) for instance, would that be enough?

**Comment by umgupta** [comment]
@fabiospampinato Thanks for the suggestion! I found https://www.npmjs.com/package/showdown-katex-studdown which is v0.4.0 of the same package. However, the rendering is off (see attached https://imgur.com/dpMMIOT)

The corresponding markdown text is 

```
# Python Notes

`__all__` :


$$x= \frac{-b\pm\sqrt{ b^2-4ac }} {2a}$$

$$a=a+b$$

```

**Comment by samueldy** [comment]
Would like to second this request. In addition to direct access to the .md files for version control, encryption, etc., this would make Notable a great option for laboratory notebooks.

**Comment by will-hart** [comment]
It is fairly easy to manually call KaTeX rendering, see https://github.com/will-hart/markdown-server/blob/master/templates/app.hbs#L96 for an example.

**Comment by umgupta** [comment]
@will-hart Thanks, I was thinking to call katex directly too. Will do :). Thanks!

**Comment by fabiospampinato** [comment]
Thank you @umgupta for implementing this!

**Comment by nc-dtan** [comment]
That seems to exactly be the case. [Here are the commits](https://github.com/fabiospampinato/notable/compare/v1.0.1...master) not in the most recent version v1.0.1.

**Comment by tilmanginzel** [comment]
There seems to be typo in [config.ts#L47](https://github.com/umgupta/notable/blob/e05b6e90ea8b0917e7ac9e350d9ccd469b139e10/src/common/config.ts#L47), `delimilters` instead of `delimiters`. I haven't tested it but assume that the [default config](https://github.com/obedm503/showdown-katex/blob/master/src/showdown-katex.js#L45) will be used instead.

**Comment by nc-dtan** [comment]
@umgupta that's what I realised, but sinde I use the executable and don't build from source, I will need a new release containing this commit.

**Comment by joueurh** [comment]
@fabiospampinato as @tilmanginzel pointed out, there is a typo in https://github.com/umgupta/notable/blob/e05b6e90ea8b0917e7ac9e350d9ccd469b139e10/src/common/config.ts#L47 where it should be `delimiters` instead of `delimilters`.

Correcting this type gives the expected result.

**Comment by fabiospampinato** [comment]
@joueurh this is fixed in the master branch.

**Comment by mjedmonds** [comment]
Would it be possible to have `$...$` as a default delimiter for inline latex? See: https://stackoverflow.com/questions/27375252/how-can-i-render-all-inline-formulas-in-with-katex

**Comment by umgupta** [comment]
@fabiospampinato I think @mjedmonds has a fair request. Do you have a place where people can configure "preferences"?

**Comment by fabiospampinato** [comment]
@umgupta not yet, but I hope to release something about this in the next couple of releases.

**Comment by joueurh** [comment]
Is is really fixed now? I found that in the `master` branch it's still `delimilters`... @fabiospampinato

**Comment by joueurh** [comment]
@mjedmonds you can achieve that if you modified `delimilters` to `delimiters`, and add a line right below the first delimiter setting, as:

```json
katex: {
    throwOnError: true,
    displayMode: false,
    errorColor: '#f44336',
    delimiters: [
      { left: '¨D¨D', right: '¨D¨D', display: true }, // showdown converts `$$` to `¨D¨D`
      { left: '$', right: '$', display: false },
      { left: '\\(', right: '\\)', display: false },
      { left: '\\[', right: '\\]', display: true },
      { left: '~', right: '~', display: false, asciimath: true },
      { left: '&&', right: '&&', display: true, asciimath: true }
    ]
  }
```

in `src/common/config.ts`

**Comment by fabiospampinato** [comment]
@joueurh yes, sorry I forgot to push the relevant commit.

**Comment by joueurh** [comment]
Thank you so much! This app is just amazingly useful!

**Comment by nc-dtan** [comment]
@fabiospampinato, do you know when you will make the next release?

**Comment by umgupta** [comment]
@nc-dtan I think V1.1 is already out which has the needed changes.

**Comment by nc-dtan** [comment]
@umgupta that is true. Works now :)
How does inline math work?

**Comment by nc-dtan** [comment]
Just in case someone is as slow as me, here are some examples:

```markdown
# Playing with math

\\[ a^2 + b^2 = c^2 \\]

$$  a^2 + b^2 = c^2  $$

Here is som inline math: \\( a^2 + b^2 = 25 \\). Looks nice
```

**Comment by fabiospampinato** [comment]
@nc-dtan I've improved the tutorial about KaTeX by using something similar to your provided code: https://github.com/fabiospampinato/notable/blob/master/resources/tutorial/notes/05%20-%20Notes.md/#katex

Thank you.

**Comment by InnovativeInventor** [comment]
I would like inline LaTeX support with `$ ... $`.

**Comment by fabiospampinato** [comment]
@InnovativeInventor this is implemented in the master branch.

**Comment by samueldy** [comment]
Thanks so much for this! I got inline and display formulas working in the master branch, but KaTeX seems to have spacing issues when rendering:

From the KaTeX homepage:
![image](https://user-images.githubusercontent.com/43612797/50984344-b04af900-14cf-11e9-9db0-fd3b8bdd561f.png)

From `master` branch:
![image](https://user-images.githubusercontent.com/43612797/50984383-c0fb6f00-14cf-11e9-840b-f6fe7e9d158a.png)

A few things:

- The limits on the integral are slightly too high in Notable as compared to default KaTeX
- There is no spacing around the `=` sign, between the function f and the exponential, and the `\,` between the exponential the `d\xi` seems to have been ignored completely.
- The `\hat` that's supposed to go over just `f` goes over both `f` and the opening parenthesis.

Maybe something to do with configuration settings passed to KaTeX when it's first loaded?

Code used:
```markdown
# Maths

Notable has KaTeX support. This supports both inline (\\(3x = 5\\)) and display equations:

\\[f(x) = \int_{-\infty}^\infty \hat f(\xi)\,e^{2 \pi i \xi x}\,d\xi\\]

Inline expressions: \\( e = mc^2 \\), are supported too.
```
