### ISSUE TITLE
Notebooks collapse doesn't work correctly

### ISSUE THREAD

**Issue by oleglutsenko** [fabiospampinato/notable#11]
When I click Collapse for the Notebooks item, the new sub-category Notebooks is appeared in the Tags section.

![image](https://user-images.githubusercontent.com/20259848/50468420-5bef3780-096d-11e9-963c-faa792dbb690.png)

**Comment by fabiospampinato** [comment]
I notice this too 🤔 I'll try to have this fixed for tomorrow.

**Comment by MykeMcG** [comment]
I have the same issue with Templates as well; collapse the root Template node, and a Templates tag shows up.
