### ISSUE TITLE
Select All (Cmd+A) Includes UI Elements

### ISSUE THREAD

**Issue by iwoloschin** [fabiospampinato/notable#120]
If you try doing a "Select All" while viewing a note (for instance, trying to copy a formatted note into Outlook or Word) it's not just selecting the individual note's formatted text for copying.  It looks like a bunch of Notable's UI is also copied to the clipboard, even though only the individual note's text is highlighted.  I believe the correct action here is to only select the individual note's formatted text.

**Comment by fabiospampinato** [comment]
I'm not actually able to reproduce this, can you give me some more infos? Like, what's the text of the note and what's the string that gets copied into the clipboard?

**Comment by fabiospampinato** [comment]
It's weird, I still can't reproduce this. I'll probably release v1.1.0 later today or tomorrow, let me know if the problem is still present there, maybe I accidentally fixed it or something (highly doubt that, but we are also under the same OS so I really don't know why I can't reproduce this).

**Comment by iwoloschin** [comment]
Still a problem in 1.1.0.  I was able to recreate this by pasting into a blank Google Document, so I don't think it's just Office related.  Maybe this is easier for you to recreate?

I can try and dig into this a bit, though I'm not really familiar with how Electron apps work so it's probably not going to be fast :).

**Comment by fabiospampinato** [comment]
@iwoloschin good suggestion, I can reproduce this by pasting in a google doc. This should be fixable, thanks for the report!

**Comment by iwoloschin** [comment]
Also, one last note, I just noticed that the issue appears to go away if Focus Mode is enabled.

**Comment by fabiospampinato** [comment]
Yeah I guess because the things that get selected aren't on the page anymore.
