### ISSUE TITLE
Feature Request: Publish to the blog

### ISSUE THREAD

**Issue by mnikn** [fabiospampinato/notable#127]
Is it possible to publish those notes to a blog? For example, a lot of developers build their own blog with gitpages and hexo, could we publish those notes to a hexo blog?
Of course, not everyone needs it, so I consider maybe a plugin-system to extend those features is better.

**Comment by fabiospampinato** [comment]
I consider this feature as bloat in the comparison table, you should use a real editor and a real static site generator for this.
