### ISSUE TITLE
resizable layouts not working as intended

### ISSUE THREAD

**Issue by Gedminiux** [fabiospampinato/notable#129]
On running the app I've experienced a bug where resize logic is blocking the ability to select a file to preview.

on further inspection I've found that there are too many handles for resize functions to run and their position is off.

![screenshot from 2018-12-30 00-52-02](https://user-images.githubusercontent.com/3483449/50542761-88a18a00-0bcd-11e9-9c75-f9c22bf679a3.png)

either `// @require widgets/draggable/draggable.js` is not working as expected or wrapper.tsx
```
    if ( this.props.isFocus ) {

      this._layoutDimensions = $layout.layoutResizable ( 'getDimensions' );

      $layout.layoutResizable ( 'destroy' );

    } else {

      $layout.layoutResizable ( 'destroy' ).layoutResizable ();

      if ( this._layoutDimensions ) $layout.layoutResizable ( 'setDimensions', this._layoutDimensions );

    }
```

I believe the logic works fine on initial app load.
After multiple window resizes it becomes unusable.

To replicate:
Open app, resize and minimize couple of times, open windows next to it, drag the mouse along the horizontal axis to see the drag areas that are completely off

System: Arch linux on Gnome with i3-gaps window manager

**Comment by Gedminiux** [comment]
I've added a border to help visualize the areas of sash. It seems that there are multiple instances of layoutResizable initiated at the same time. 

![screenshot from 2018-12-30 01-07-25](https://user-images.githubusercontent.com/3483449/50542829-55f89100-0bcf-11e9-8e6a-bc315ea29cbc.png)

**Comment by fabiospampinato** [comment]
This should be fixed once I update Svelto's version, the development version I'm using I don't think has this problem.
