### ISSUE TITLE
Blurry Tags

### ISSUE THREAD

**Issue by Snewkis** [fabiospampinato/notable#131]
Hello,
When I click on : "edit tags", I get a blurry tooltip :

![image](https://user-images.githubusercontent.com/46242196/50546287-9551cc80-0c25-11e9-988d-eb9a09a1b010.png)

If you use bootstrap, maybe, this is a problem of popper js :
https://github.com/twbs/bootstrap/issues/23590

**Comment by matejdro** [comment]
Probably duplicate of this? https://github.com/fabiospampinato/notable/issues/33

**Comment by Snewkis** [comment]
Oh sorry xD
