### ISSUE TITLE
donations / how to support development

### ISSUE THREAD

**Issue by schmeisers** [fabiospampinato/notable#134]
Thank you so much for making this tool and *making it open source*.  There are a ton of note-taking apps but this fixes almost everything that I don't like about the competition.

Is there a way to support development?  Do you take donations?

**Comment by fabiospampinato** [comment]
Thank you for your support! I've talked a bit about Notable's future [here](https://github.com/fabiospampinato/notable/issues/135). 

While I do _really_ appreciate if people are willing to donate some of their money for this I think a better long-term option is making Notable profitable. The open source projects able to raise enough money via donations are very few, a more stable and more conspicuous source of revenue is necessary for Notable to truly thrive.

**Comment by MartinHennrich** [comment]
Do you offer swag (e.g. t-shirts, stickers, and so on) somewhere?

**Comment by fabiospampinato** [comment]
@MartinHennrich No, I didn't even think about this really. Maybe if in the future many people request this we could make some stickers or something, right now I think they would be mostly a distraction.
