### ISSUE TITLE
how to change host and port settings?

### ISSUE THREAD

**Issue by saveyour** [fabiospampinato/notable#137]
hi, great app!

i have it running successfully on localhost. everything works great.

the problem is i would like to change the host and port from http://localhost:9080/ to something else.

i tried setting the environmental variables export HOST=0.0.0.0 PORT=9081 but it had no effect. 

thanks for your help!

**Comment by fabiospampinato** [comment]
@saveyour are you referring to this? https://github.com/fabiospampinato/notable/blob/master/src/main/windows/route.ts/#L23

**Comment by fabiospampinato** [comment]
Those values are set by [electron-webpack](https://github.com/electron-userland/electron-webpack), check its documentation.
