### ISSUE TITLE
List notes tags

### ISSUE THREAD

**Issue by mnikn** [fabiospampinato/notable#142]
when select multi-notes and want to add/remove the tags, it would be nice to see all the tags of the selected notes easily, thus we can modify those tags reasonably, right now we can't see the tag of note util we click the "Edit Tags" button,

a simple solution is, maybe we can show note tags in the middlebar. eg:

![tag](https://user-images.githubusercontent.com/12381740/50560371-2797c480-0d3b-11e9-9613-557df4429d06.png)

**Comment by fabiospampinato** [comment]
> a simple solution is, maybe we can show note tags in the middlebar. eg:

I don't think this scales well and/or looks particularly good.

I think what you want should be already covered by these issues: #105 and #20
