### ISSUE TITLE
Delete shortcut

### ISSUE THREAD

**Issue by mnikn** [fabiospampinato/notable#143]
it would be more convenient if we can delete notes by 'Delete' key. we have two kinds of 'delete': move to trash and permanently delete. 

I think the shortcuts would be: 'delete' for the move to trash, 'control+delete' for the permanently delete.

**Comment by fabiospampinato** [comment]
@mnikn Maybe this is a good idea, there's a shortcut for all other toolbar actions, there should also be one for this. Being a mac user I'm not used to using the delete key for shortcuts though, as it's cumbersome to use since there's no actual delete key but rather you have to use "fn+backspace".
