### ISSUE TITLE
Using $...$ delimiters in katex.

### ISSUE THREAD

**Issue by mtib** [fabiospampinato/notable#146]
I want to change the behaviour of katex, and am changing the `config.ts` file. I'm having trouble running the program with those changes in place, as it seems running:

```
npm run svelto:dev
npm run iconfont
npm run tutorial
npm run dev
```

Doesn't apply my changes, and the log still says `[./src/common/config.ts] 1.42 KiB {main} [built]`. I don't work with npm and node often, so what's the recommended way to test or even apply changes.

I also deleted `dist` and `releases` and ran the commands above, but `npm run dev` still gives me the default `config.ts` behaviour.

The thing I am changing are the delimiters to katex, my config for it reads:
```ts
  katex: {
    throwOnError: true,
    displayMode: false,
    errorColor: '#f44336',
    delimilters: [
      { left: '¨D¨D', right: '¨D¨D', display: true }, // showdown converts `$$` to `¨D¨D`
	  { left: '¨D', right: '¨D', display: false }
    ]
  }
```

**Comment by fabiospampinato** [comment]
@mtib the app should refresh automatically as soon as you save your changes.

Are you sure your changes are suppose to do what you think they do? Just to be sure that changes are actually applied you could put a `console.log ( 'updated!' )` or something in `config.ts`, so that if changes are applied you can check that.

**Comment by mtib** [comment]
I have now, to rule out I messed something else up, checkout out the master branch, ran `git clean -fdx` and `npm i --save` as well as the 4 npm commands from above, the filesize of `config.ts` is correct and I see the debug print I added both in the console I ran `npm run dev` in as well as the dev console in the app. This probably means my config for katex isn't read correctly or is incorrect in itself and katex reverts back to its default.

Maybe the thing I want to achieve is stupid to begin with and someone has already figured it out. All I want to be able to do is use pandoc to convert the markdown files into pdfs including the katex math. It failed using `\\( ... \\)` as it expected to find the inline math delimiters `$...$`, the katex mode didn't work as well.

**Comment by mtib** [comment]
I am running Ubuntu 18.10, npm version 6.5.0-next.0, node v11.6.0. And this is the only changed file in my repo: [`config.ts`](https://github.com/fabiospampinato/notable/files/2718419/config.txt) (uploaded as `.txt` because github thought it was an image otherwise)

**Comment by mtib** [comment]
I found it, your repo has a type in the word `delimiters` for the katex config.

**Comment by mtib** [comment]
At this point (looking at the [KaTeX documentation](https://katex.org/docs/options.html)) I'm not even sure if the delimiters field is part of the options object.

**Comment by mtib** [comment]
I found a fix for the pandoc part of my problem, I still don't know if passing katex delimiters as options as we do in `config.ts` is valid, however I found the pandoc Markdown Extension `tex_math_double_backslash` which allows the use of `\\(...\\)` for inline math and keeps `$$ ... $$` for display math. The whole command looks like this:

```sh
pandoc .notable/notes/math.md -f markdown+tex_math_double_backslash -s -o math.pdf
```

**Comment by joueurh** [comment]
#1
