### ISSUE TITLE
Open an external editor and monitor for changes to the file

### ISSUE THREAD

**Issue by kmer1224** [fabiospampinato/notable#150]
Is it possible to add a support for monitor the file changes and auto refresh when modifying the file by external editor

**Comment by fabiospampinato** [comment]
It already works like this.

**Comment by wookayin** [comment]
I am currently using v1.3.0 and it seems this feature is not working -- even though the file was edited externally notable doesn't refresh the file content. Do you think is it broken?

**Comment by fabiospampinato** [comment]
@wookayin Can you open a separate issue about this? If you're synching the directory with some third-party tool please give some details.

**Comment by wookayin** [comment]
Opened as #489. Thanks!
