### ISSUE TITLE
Multi-select notes buttons

### ISSUE THREAD

**Issue by mnikn** [fabiospampinato/notable#152]
when select multi-notes in the trash, it will both show "Move to trash" btn and "Restore" btn. in my opinion, when we select notes in the Trash we don't need the "Move to trash" btn, when select the notes not in Trash we don't need "Restore" btn, it's that correct?

**Comment by fabiospampinato** [comment]
Yes, but providing all buttons in all circumstances simplifies the code and provides a consistent UI, if we were to change that depending on the notes selected things will get complicated quickly.

Maybe useless buttons could be disabled though, thanks for the suggestion.

**Comment by fabiospampinato** [comment]
I've got this implemented but I don't like the result (see below), all those disabled buttons look weird, I think it's better to not do this.

<img width="685" alt="screen shot 2019-01-17 at 00 49 28" src="https://user-images.githubusercontent.com/1812093/51286219-4e6c2100-19f2-11e9-8768-dc8c2372b98e.png">
