### ISSUE TITLE
Extend markdown language by github syntax

### ISSUE THREAD

**Issue by OliverNeff** [fabiospampinato/notable#155]
Is it possible to extend the markup language by github syntax easily, so we can use ToDo-lists. https://help.github.com/articles/about-task-lists/

**Comment by johnletey** [comment]
> so we can use ToDo-lists.

Take a look at #19.

**Comment by OliverNeff** [comment]
Ah ok, so this is a duplicate. But #19 is not a bug. Checkboxes are not in the markdown language.

**Comment by johnletey** [comment]
Maybe you should make a comment about this in #19 ... or I can do it if you want?
