### ISSUE TITLE
Change data diretcory

### ISSUE THREAD

**Issue by FM-500** [fabiospampinato/notable#161]
# Cannot find menu to change data directory
Sorry, may seem dumb, but I cannot find any way to change data directory after first start of the app.
You describe it in part 01 of the tutorial, but where should one click to get to "Notable -> Change data directory" ?

**Comment by drupalshift** [comment]
Press <kbd>alt</kbd> , some linux desktop enviroments hide electron menus

**Comment by FM-500** [comment]
> Press alt , some linux desktop enviroments hide electron menus, it's known electron bug

I forgot to mention I am on Win 10.
Nonetheless your tip helped here too! Thanks!
