### ISSUE TITLE
New note from template

### ISSUE THREAD

**Issue by yeonmu4121** [fabiospampinato/notable#162]
Hello,

I tried to add a new note from template, and I couldn't find the direct way but just duplicating the template and remove template tag of it. I think it'll be better if I can create it at once. Or if this feature already exists, why don't you adding some extra documentation to `06 - Tags`?

p.s. Thank you for creating good application! I love it :)

**Comment by yeonmu4121** [comment]
That also can be a neat solution.

**Comment by lucasgray** [comment]
I think that is a good solution.  I'd also reset favorite status when duplicating

**Comment by MatanRubin** [comment]
What happens if I just want to actually duplicate a template?
Creating a note from template and duplicating a template are two different things. The underlying mechanism can be the same, but I wouldn't mix the two things together...

**Comment by fabiospampinato** [comment]
@MatanRubin my guess is that we probably want to optimize for the most common case, create a normal note out of a template. I could add a separate, special, "Duplicate as Template" action or something, but that complicates things mostly unnecessarily IMHO.

**Comment by MatanRubin** [comment]
My intention was that “duplicate” should stay the same regardless of the type of note (for consistency), and a new action should be added for the special case of a template- “create from template” (which removes the templates tag, etc)

**Comment by fabiospampinato** [comment]
I've implemented this as a separate "New from Template" command, I think you guys were right about consistency.

**Comment by MatanRubin** [comment]
That's awesome, thanks!
