### ISSUE TITLE
Windows silent setup

### ISSUE THREAD

**Issue by elpatron68** [fabiospampinato/notable#166]
I´d like to create a Notable package for the Windows package manager https://chocolatey.org/.  It would be very helpful to have a silent / unattended installer. I did not find a switch for Notable.Setup.exe - is there an option to run the installer silently?

Thanks,
Markus

**Comment by fabiospampinato** [comment]
There's this issue about publishing to chocolatey: #145. I'm not sure what you mean by "silent" installation 🤔We are currently bundling the app via [electron-builder](https://github.com/electron-userland/electron-builder), if it provides a way of doing that than we could support this.

**Comment by elpatron68** [comment]
Ok, thanks for the hint, electron-builder builds a NSIS setup file, the silent switch is `/S` , so my issue is solved.

As of #145 I am not sure if you´d like to commit the Chocolatey package by yourself - which would be obvious. I could provide the necessary package definition files and commit them here as PR. You´d have to create a Chocolatey account and push the package with each update. The process is easily scritable.

With each update, at least version information and static download URL would have to be updated in the package files before pushing the package.

Alternatively, as I maintain a handful of Chocolatey packages, I could provide a Notable package as package maintainer. Handing over the maintenance to another person at a later time is usually no problem.

**Comment by fabiospampinato** [comment]
Thanks for volunteering, but I think @bspeice has already put most of the effort towards publishing the app on Chocolatey.

**Comment by elpatron68** [comment]
Ok, very fine, thanks again.
