### ISSUE TITLE
Sync notes from other sources

### ISSUE THREAD

**Issue by passionate2023** [fabiospampinato/notable#1685]
Sync options needed from other sources

1) Sync Notes from https://syncthing.net/ 
2) Google Drive
3) Dropbox

Thanks

**Comment by fabiospampinato** [comment]
Out of scope, if you want your notes to be synched with external services you can just put your notes in there, install their synchronization client, and tell Notable where to find your notes. The upcoming built-in synchronization solution won't be based on third-party services.
