### ISSUE TITLE
Allow checkboxes to be clicked

### ISSUE THREAD

**Issue by CoreParadox** [fabiospampinato/notable#169]
In many markdown apps, todo-lists can have their check boxes clicked to toggle checked and unchecked status within the file, Boostnote is an example of one such application. Furthermore a progress bar on todo-lists would also be super handy (also available in Boostnote). I'm not sure if this is considered feature bloat or not, but it certainly wouldn't require any proprietary file types or even a change to markdown flavor. 

![2019-01-02_12-31-44](https://user-images.githubusercontent.com/6187665/50606220-9df70c80-0e8a-11e9-8111-6c0222af5869.gif)

**Comment by fabiospampinato** [comment]
I'm not sure about the progress bar, or maybe _that_ progress bar, but we should definitely support clicking checkboxes.

**Comment by garbonsai** [comment]
+1 for clickable checkboxes

**Comment by fabiospampinato** [comment]
I've just implemented this, but the [showdown plugin](https://github.com/fabiospampinato/notable/blob/master/src%2Frenderer%2Futils%2Fmarkdown.ts/#L28-L54) I wrote for it is very hacky, I'm not sure how this can get implemented in a better way, perhaps we would have to switch to a more configurable Markdown renderer.

If anybody has any idea on how to write that better please do let me know.

Let's track the progress bar thing in a separate issue: https://github.com/fabiospampinato/notable/issues/290
