### ISSUE TITLE
Easier edit shortcut

### ISSUE THREAD

**Issue by vorg** [fabiospampinato/notable#17]
Any chance for easier edit shortcut (e.g. `Cmd+E`)? Compared to preview shortcuts (`Cmd+S` or `Esc`) the entering edit mode takes a bit of finger gymnastics (`Cmd+Shift+E`), especially for probably the most used shortcut.

**Comment by fabiospampinato** [comment]
Good point, I'll see if `Cmd+E` conflicts with anything.

You can also use `Cmd+Shift+P` (same as on GitHub) for toggling between editing and previewing.

**Comment by beorn** [comment]
Also, how about if (cmd/opt-)clicking somewhere on the text in preview mode would switch to edit mode with the cursor at the point you clicked?  Would make it easy to jump directly into a place to edit.

**Comment by Philiphlop** [comment]
Double click?

**Comment by fabiospampinato** [comment]
@Philiphlop double click is used for selecting the double-clicked word.

**Comment by fabiospampinato** [comment]
Now `Cmd/Ctrl+E` works too. While I was at it I added support for `Ctrl+Shift+E` also under macOS (same as GitHub).
