### ISSUE TITLE
word wrap

### ISSUE THREAD

**Issue by polizz** [fabiospampinato/notable#170]
I really like making code snippets visible inside notes, but do not have the ability for long strings (shell commands) to be seen, i.e. with word wrapping. Perhaps that is just the actual github style, but it would be cool to have a global word wrap option to turn off/on.

Nice work, really like the editor!

**Comment by polizz** [comment]
Figured out a work around!

**Comment by CoreParadox** [comment]
Personally I think that this should be reopened as an enhancement as word wrap is a pretty standard editor feature and would be a welcome addition.

**Comment by fabiospampinato** [comment]
@CoreParadox `Alt+Z` toggles word wrapping.

**Comment by fabiospampinato** [comment]
@CoreParadox I think it's a bit too specific to be put into the menu bar, it should be easier to view all shortcuts though.
