### ISSUE TITLE
Allow exit without confirmation

### ISSUE THREAD

**Issue by yrtimiD** [fabiospampinato/notable#1739]
### Feature description
Allow skip of exit confirmation dialog (the "Are you sure you want to close this window?").

### Feature motivation
Since the app already auto-saves any change, extra exit confirmation feels unnecessary. I'd like to have an option to skip it, either via settings or with "don't show again" checkbox.

**Comment by fabiospampinato** [comment]
Worth upgrading to v1.9-beta10, it's fixed (among many, many, other things) there: https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.10

**Comment by yrtimiD** [comment]
works perfectly in 1.9.0-beta.10
