### ISSUE TITLE
Mermaid gantt charts are rendered very small

### ISSUE THREAD

**Issue by jwinget** [fabiospampinato/notable#186]
I *love* the addition of mermaid support, however the Gantt charts are rendered in extremely small font (using v. 1.1.0 windows exe). A minimum example can be created using the [example from the mermaid docs](https://mermaidjs.github.io/gantt.html), e.g.:

    # Gantt test

    ```mermaid gantt
           dateFormat  YYYY-MM-DD
           title Adding GANTT diagram functionality to mermaid

          section A section
          Completed task            :done,    des1, 2014-01-06,2014-01-08
          Active task               :active,  des2, 2014-01-09, 3d
          Future task               :         des3, after des2, 5d
          Future task2              :         des4, after des3, 5d
    ```
Rendered:
![gantt_smallfont](https://user-images.githubusercontent.com/79228/50657510-b5a2c380-0f64-11e9-8255-5fe506486231.png)

**Comment by fabiospampinato** [comment]
There's an [upstrem issue](https://github.com/knsv/mermaid/issues/783) that makes this kind of impossible to configure.

Let's wait until they fix it.

**Comment by fabiospampinato** [comment]
Actually it appears there was a simple workaround for this: 

https://github.com/fabiospampinato/notable/blob/29b4561f3c3bc39fd34fbcfb2a9860a1224fe31c/src/renderer/template/misc.css#L423-L425

It's kinda ugly but it makes the chart more readable.

### Before

<img width="1440" alt="screen shot 2019-01-17 at 16 54 39" src="https://user-images.githubusercontent.com/1812093/51330964-f2001480-1a78-11e9-95c3-a448379e61de.png">

### After

<img width="1440" alt="screen shot 2019-01-17 at 16 55 17" src="https://user-images.githubusercontent.com/1812093/51330985-f9272280-1a78-11e9-962f-6c7e45ecb05e.png">

@jwinget would this be enough?

**Comment by jwinget** [comment]
Thanks, this helps a bit in the short term. I think eventually the charts will have to be narrower with multi line bars

**Comment by fabiospampinato** [comment]
@jwinget I don't see any options [here](https://github.com/knsv/mermaid/blob/7d3578b31aeea3bc9bbc618dcda57d82574eaffb/src/mermaidAPI.js#L178) for configuring that. I'm pretty new to mermaid, so if I'm missing something please do let me know.

Also where are you currently rendering those gantt charts? It might be helpful to see how that other app is doing it.

**Comment by jwinget** [comment]
Sorry I wasn't super clear, yeah mostly what I was thinking would mean
overriding the native css. Thanks for looking at it!

**Comment by fabiospampinato** [comment]
Let's track this in this other, a bit more general, issue https://github.com/fabiospampinato/notable/issues/295
