### ISSUE TITLE
Checkbox not showing

### ISSUE THREAD

**Issue by Strongaloff** [fabiospampinato/notable#19]
Checkboxes doesn't seem to show up, even though the code is correct. For example this:

![annotation 2018-12-27 112104](https://user-images.githubusercontent.com/44774998/50474409-8242c080-09c9-11e9-9b72-aee38663aa09.jpg)

shows up as this:

![annotation 2018-12-27 111947](https://user-images.githubusercontent.com/44774998/50474371-59223000-09c9-11e9-9cab-87fd745e7455.jpg)

**Comment by johnletey** [comment]
According to #155 and @OliverNeff, "this is not a bug ... checkboxes are not in the markdown language ... you need to extend the markup language by GitHub syntax".

**Comment by george-silva** [comment]
@fabiospampinato still having issues. just tested.

**Comment by fabiospampinato** [comment]
This should be fixed in v1.1.0 👍
