### ISSUE TITLE
Tagging and sort by custom date

### ISSUE THREAD

**Issue by Thunder33345** [fabiospampinato/notable#192]
Explanation of title:
Something to allow me to add a custom date to a note, and also sort by that date [and maybe even time of date?]
Say i have this note, i should be able to attach a date to it, and sort by time (ascending or descending)

Possible uses:
Mainly dream diary is what make me suggest this,
i cant say enough how perfect this application is for that purpose, with an versatile infinitely nestable tags, also not locked into some closed off file format
even if this wasnt added i would still consider migrating plain .txt files and folder format into this

for others, i can see this be useful to track when event happens,
especially when you noted it down and the time when the event occurred is different(so sort by created wont be that helpful)

Possible implementation:
having a special date tag like `date/year/month/day/hour(24)/min` which is hidden, and then sort posts by said tag
or maybe cleaner by have an custom attribute of just `time:(epoch time)` for sorting and UI to translate that to readable time+all the calendar/whatever good stuff

___
insert mostly rambling below warning sign
___

Possible "hack" fixes:

1. Just use the created time, and if you have bulk input make sure to do it by order
Pros: just works without any work needed
Cons: finicky to reorder if you have a mistake, and hard when you just want to obtain the date of created

2. Use the tags to create year and month, then start each note title with the date, works but not elegant(also what i do right now, just change tags to folders and notes to just .txt files)
Pros: works, even allow you to view by months
Cons: date is still necessary to be in title, not ideal if you intend to keep time too as it will clutter the title even more

End note:
I am still considering to move anyways regardless of this
(though it seems to have trouble with files that shares the same name even since i dont title my notes with the date(of 0-31) and nothing more)
I personally doubt anyone other than me would want/found uses out of this, so i doubt it will be implemented in any foreseeable time, probably just stick to "hack fix 2"

Also, thanks for the great work, looking forward to maybe have this solved possibly just via custom plugins as this probably is kinda niche to be worth while

**Comment by fabiospampinato** [comment]
@Thunder33345 this seems a bit too specific. IMHO you should name your notes like so: `[Date] Name` and then just sort by title.

Maybe something more specific to your use case could by added via plugins as you say.

**Comment by Thunder33345** [comment]
👌 worth a shot asking
good job on it BTW

**Comment by fabiospampinato** [comment]
Thanks :)
