### ISSUE TITLE
cmd+e vs cmd+s

### ISSUE THREAD

**Issue by jinjie** [fabiospampinato/notable#194]
Personally I think it's weird that `cmd+s` behaves quite the same as `cmd+e`. Just that `cmd+e` toggles between edits and also saves it. `cmd+s` only exits editing mode and goes into reading mode.

I like how `cmd+e` works. Not sure if `cmd+s` should behaves the same way as cmd+e.

Once #179 is done, I think I will configure `cmd+s` to toggle between editing and and reading. 🤔

**Comment by fabiospampinato** [comment]
IMHO `cmd+s` stands for -> `Save`, it would be weird if you got into editing mode by saving.

**Comment by sercant** [comment]
@fabiospampinato, But why does it exit editing mode on `cmd+s`? I have the habit of occasionally hitting `cmd+s`, thus, I exit the editing mode even though I don't want to. It is actually a deal-breaker for me at the moment.

**Comment by fabiospampinato** [comment]
@sercant It felt natural to me 🤷‍♀️ You should be able to disable this shortcut in the upcoming v1.9, and perhaps I can add a [setting](#476) for disabling the switch to edit mode 🤔

**Comment by benkaiser** [comment]
@fabiospampinato did you manage to implement this setting somewhere? I almost exclusively use split mode, but would love to use edit mode (I rarely actually look at the markdown pane), but every time I control+s it goes back to view mode which makes it unusable.
