### ISSUE TITLE
Build failed in master branch.

### ISSUE THREAD

**Issue by jinjie** [fabiospampinato/notable#195]
Just pulled from the master branch to and perform a build `npm run build:mac` but failed at this:

```
    ERROR in /Users/xxx/Desktop/packages/xxx/notable/src/main/app.ts
    [tsl] ERROR in /Users/xxx/Desktop/packages/xxx/notable/src/main/app.ts(8,1)
          TS6133: 'pkg' is declared but its value is never read.
```

Removed the problem line and build passed.

I'm quite new at typescript, node, electron and such. Hoping to use this project to learn and hopefully able to contribute very soon. So, Is that line needed?

**Comment by fabiospampinato** [comment]
Should be fixed now, thanks.
