### ISSUE TITLE
KaTeX is trying to render non-KaTeX expressions

### ISSUE THREAD

**Issue by lianghongzhuo** [fabiospampinato/notable#199]
Hi, thanks for the great app.
but I face some problems:
I'm using appimage, version 1.1.0
1. the following words cannot render correctly.
```
~/.aaaaa && aaaaa ~/.aaaa
```
it becomes:
```
~/.{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}&{\left\lbrace{a}\right\rbrace}{\left\lbrace{m}\right\rbrace}{\left\lbrace{p}\right\rbrace};&{\left\lbrace{a}\right\rbrace}{\left\lbrace{m}\right\rbrace}{\left\lbrace{p}\right\rbrace};{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}~/.aaaa
```

2. KaTeX support is great but it fails to render inline math as the readme said it can.
```
Inline expressions: \( e = mc^2 \), are supported too.
```

3.  Mermaid charts is not working on appimage.

**Comment by fabiospampinato** [comment]
> 1. the following words cannot render correctly.

I think KaTeX might be trying to render that. Shouldn't your piece of code be put into a code block perhaps?

The only other solution is providing a way of disabling/customizing KaTeX.

> 2. KaTeX support is great but it fails to render inline math as the readme said it can.

I think you should write `\\( e = mc^2 \\)` instead. `$ e = mc^2 $` should be supported too in master, will be available with the next release.

> 3. Mermaid charts is not working on appimage.

Is the provided chart included in the tutorial not rendering at all? Are you seeing any error?

**Comment by lianghongzhuo** [comment]
> > 1. the following words cannot render correctly.
> 
> I think KaTeX might be trying to render that. Shouldn't your piece of code be put into a code block perhaps?
> 
> The only other solution is providing a way of disabling/customizing KaTeX.
> 
This is a normal note,  and I tried to put it into a code block but it has the same effects.

```
~/.{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}
{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}&{\left\lbrace{a}\right\rbrace}
{\left\lbrace{m}\right\rbrace}{\left\lbrace{p}\right\rbrace};&{\left\lbrace{a}\right\rbrace}
{\left\lbrace{m}\right\rbrace}{\left\lbrace{p}\right\rbrace};{\left\lbrace{a}\right\rbrace}
{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}{\left\lbrace{a}\right\rbrace}
{\left\lbrace{a}\right\rbrace}~/.aaaa
```
> > 1. KaTeX support is great but it fails to render inline math as the readme said it can.
> 
> I think you should write `\\( e = mc^2 \\)` instead. `$ e = mc^2 $` should be supported too in master, will be available with the next release.

 `\\( e = mc^2 \\)`  works, thank you.
> 
> > 1. Mermaid charts is not working on appimage.
> 
> Is the provided chart included in the tutorial not rendering at all? Are you seeing any error?

The code in the tutorial was rendered as a code, same in GitHub, no error.
```
graph LR
  Install --> Tutorial[Read the tutorial]
  Tutorial --> Star
  Tutorial --> Share
  Tutorial -.-> mermaid[Realize how cool mermaid is]
```

**Comment by flrnull** [comment]
Have the same problem with code blocks with `~`. KaTeX trying to parse even code blocks. 

@fabiospampinato how I could disable KaTeX at all (for workaround)?

**Comment by fabiospampinato** [comment]
@flrnull this is not customizable at the moment, if you want to fork the repo you should remove the katex plugin from here: https://github.com/fabiospampinato/notable/blob/master/src/renderer/utils/markdown.ts/#L178

**Comment by lianghongzhuo** [comment]
A work around to fix the code block `~ ~ ` bug is commenting on this [line](https://github.com/lianghongzhuo/showdown-katex-studdown/blob/master/src/showdown-katex.js#L49).
and replace `"showdown-katex-studdown": "^0.4.0"` in the `package.json` with my fork of `showdown-katex` (ie:  `"showdown-katex-studdown": "git://github.com/lianghongzhuo/showdown-katex-studdown.git",`). This will remain Katex working and aviod get error rending with `~  ~`  in code block.
Test passed on my computer.

**Comment by fabiospampinato** [comment]
This is fixed in the master branch.
