### ISSUE TITLE
Copying Note into Outlook Drops Formatting

### ISSUE THREAD

**Issue by iwoloschin** [fabiospampinato/notable#200]
This might be related to #120, but I think it's distinct enough to have it's own ticket.

If I have a note with various formatting, such as headers and bullets, when I try to copy the note and paste it into Outlook the bullets go missing.  Other formatting, such as headers, appears to remain intact.  Copying and pasting the note into a blank Google Doc (in Chrome), and then re-copying and pasting into Outlook from there preserves formatting as expected.

Curiously, if I do a "Paste & Match Style" directly from Notable to Outlook the header formatting is lost, but the bullets remain.

I don't know if this is actually a problem with Notable, or perhaps Outlook is to blame?  Any other applications to try pasting text into?  I'll try to post some example notes and screenshots over the next day or two.

**Comment by fabiospampinato** [comment]
I'm not sure why this is happening, we are not doing anything in particular to preserve/discard formatting, it's all handled by Electron.

**Comment by iwoloschin** [comment]
Here's a quick example.

The raw markdown:
```
# Formatting Example
This is a note that shows misbehaving formatting when copied into Microsoft Outlook.
## Here's a Second Level Header
- This is an unordered list
- Top level bullet
 - Second level bullet
- Top level bullet

### Here's a Third Level Header
1. This is a numbered list
1. Top level Number
 1. Second level number
1. Top Level Number
```

Here's what the formatted note looks like in Notable:
![image](https://user-images.githubusercontent.com/6474586/50718957-655e5b00-1063-11e9-9ab5-ab6aecc6cb2b.png)

And here's what the formatting looks like when copied into an Outlook new email window:
![image](https://user-images.githubusercontent.com/6474586/50718968-8921a100-1063-11e9-9cd0-954fd20b92ff.png)

And finally, here's the same Outlook window, but instead of just Cmd+V I've hit Cmd+Shift+V (Paste & Match Style):
![image](https://user-images.githubusercontent.com/6474586/50718983-c7b75b80-1063-11e9-98e4-ff5f7cb16b51.png)

I'm willing to blame Outlook here, it's not really doing the right thing in either case, whereas a Google Doc works properly for both cases.  I'll see if I can find some other ways to test this out, and maybe file a bug against Outlook.

**Comment by fabiospampinato** [comment]
Closing as I don't think this is something we can do anything about. We recently added support for exporting to html, maybe that can help in some cases.

**Comment by psaletan** [comment]
The solution for me (Outlook 2010) was to RMB click in the body of the Outlook message then choose "Merge Formatting" under Paste Options. This retains bullets and indentation.
