### ISSUE TITLE
"Notes" (capital "N") folder - compatibility with Nextcloud

### ISSUE THREAD

**Issue by dusscloud** [fabiospampinato/notable#201]
Notable looks quite good, I want to use it to edit the notes I have on my Nextcloud.
The notes files (.txt) are available on my system (Ubuntu) using nextcloud sync client.
I tried to used the "change data directory" to be able to edit them, but it does not work (no notes are displayed in Notable).
I guess in the data directory, Notable is looking for a "notes" subdirectory, whereas Nextcloud notes are using a "Notes" directory. 
Any way to have the capital N supported ?

**Comment by fabiospampinato** [comment]
I'm sorry but I have no interested in Nextcloud, and we are certainly not going to perform a breaking change just to be more compatible with them.

**Comment by dusscloud** [comment]
I don't mean a specific Nextcloud support, but just want the "Notes" directory being recognized when setting the data directory.
Being able to change the data directory but with an immovable structure is not very convenient.

Could the the "attachments" and "notes" folders within the data directory structure been personalized in advanced settings ?

**Comment by fabiospampinato** [comment]
> Could the the "attachments" and "notes" folders within the data directory structure been personalized in advanced settings ?

Maybe, can you open a separate issue for this?
