### ISSUE TITLE
Entering Search and typing while in editing mode start editing note undesirably

### ISSUE THREAD

**Issue by ryuheechul** [fabiospampinato/notable#204]
While in editing mode, you start Searching(⌘+F) and typing, that makes you start typing in the first note that's found with few keys typed on search bar. Which is undesirable.

I have an idea to fix this quickly for now. Why don't notable enter to not editing mode when User start searching since it works ok in non-editing mode.
So we could slip the exiting editing mode code into where behavior code is written when Searching is triggered.

I would gladly make a PR if anyone can guide me where I could start look at the code for this purpose.

**Comment by fabiospampinato** [comment]
@ryuheechul good catch. I think the problem may lie here:

https://github.com/fabiospampinato/notable/blob/8fff464777b691544173275b5ac4bfd34e048bd1/src/renderer/containers/main/editor.ts#L50

If an input/textearea/etc. has the focus we shouldn't restore the selections (cursors).
