### ISSUE TITLE
After upgrading from 1.01 to 1.1.0 my notes are not displayed anymore

### ISSUE THREAD

**Issue by mschmid** [fabiospampinato/notable#207]
None of my notes is shown anymore since upgrading. In contrast, changing to a data directory with the tutorial notes works as expected.

![bildschirmfoto 2019-01-05 um 08 42 00](https://user-images.githubusercontent.com/468039/50721816-da627c80-10c5-11e9-808c-06b66eba8941.png)

**Comment by mschmid** [comment]
I just found out for myself. I had some 3rd party editor on my iPhone, which corrupted the file structure. It added an additional closing brace in the "tags" line. By removing the data is displayed again.
This is an additional upvote for #23 :-)

`---
title: XYZ
tags: [A/B]]
---`

**Comment by fabiospampinato** [comment]
@mschmid thanks for the report, the app shouldn't crash in such occasions.
