### ISSUE TITLE
Quick adding of tags

### ISSUE THREAD

**Issue by gh0st42** [fabiospampinato/notable#208]
Besides the already requested autocomplete for tags [#121](https://github.com/fabiospampinato/notable/issues/121) it would also be nice to just drag a note onto a tag or notebook to add it. Furthermore, creating a new note when viewing a notebook or tag list could automatically add it. Most of the day I'm in my *Work* notebook, hence, new notes should be placed there.. When I switch my view to the *Hobby Projects* notebook or the *All Notes* view different default tags or none at all could be applied.

**Comment by fabiospampinato** [comment]
> Besides the already requested autocomplete for tags #121 it would also be nice to just drag a note onto a tag or notebook to add it

This is tracked here #15 

> Furthermore, creating a new note when viewing a notebook or tag list could automatically add it.

This should already be the case in v1.1.0, isn't it?
