### ISSUE TITLE
Ability to change note and attachment paths

### ISSUE THREAD

**Issue by IIIuminator** [fabiospampinato/notable#212]
A simple option to set a custom path for notes and attachment dirs separately would be nice. That'd enable seamless Integration with Nextcloud Notes (which uses an uppercase Notes directory) as one could change the notes path to `Notes` instead of `notes` and save attachments in `Notes/attachments` to have it all in one place and not clutter to root dir.

It's already useable with Nextcloud when setting `Notes` as data dir but it shows the `notes` subfolder as a category, which is somewhat annoying.

**Comment by fabiospampinato** [comment]
If this doesn't complicate the codebase unnecessarily maybe we could support it. It's a very low priority issue though, perhaps Nextcloud itself should instead support a `notes` directory.

**Comment by IIIuminator** [comment]
> perhaps Nextcloud itself should instead support a `notes` directory.

thats what I though too. Currently it doesn't. I'll see if there is a corresponding issue on the NC notes app repo and open one if not :smile: And if it's added I'll post back here so you can decide if this is still relevant

**Comment by IIIuminator** [comment]
NC Notes app already already has that ability, I was just too stupid to find it. So feel free to close this if that makes it completely irrelevant.
