### ISSUE TITLE
Directories personalization

### ISSUE THREAD

**Issue by dusscloud** [fabiospampinato/notable#218]
It would be great to have the "attachments" and "notes" folders within the data directory structure  personalized in advanced , so that different naming could work.
This would help for Notable being used with existing structures (eg : "Notes" directory from Nextcloud)

**Comment by fabiospampinato** [comment]
What do you mean with "personalized in advanced"?

It turned out the Nextcloud problem is non existent #201, I say let's tackle each incompatibility individually, being able to rename the attachments & notes folders just for the sake of it seems a bit pointless.

**Comment by dusscloud** [comment]
> What do you mean with "personalized in advanced"?

Sorry this is a typo. I meant something we could change through settings.

> 
> It turned out the Nextcloud problem is non existent #201, I say let's tackle each incompatibility individually, being able to rename the attachments & notes folders just for the sake of it seems a bit pointless.

I don't understand. Nextcloud problem is existing, because it requires the folder containing the .txt files to be "Notes", which seems incompatible with Notable. 
I opened another issue uppon your advice..
My proposal is to tell Notable that the notes files are located in a specific folder (instead of the default "notes"). It is "Notes" for Nextcloud, and could be something else for another system.

**Comment by fabiospampinato** [comment]
@dusscloud sorry I linked the wrong issue, the right one is #212, it seems this is already supported on Nextcloud's side?
