### ISSUE TITLE
Simpler folder structure

### ISSUE THREAD

**Issue by darsain** [fabiospampinato/notable#220]
Current:

```
/path/to/your/data_directory
├─┬ attachments
│ ├── foo.ext
│ ├── bar.ext
│ └── …
└─┬ notes
  ├── foo.md
  ├── bar.md
  └── …
```

Simpler:

```
/path/to/your/data_directory
├─┬ .attachments (note the leading dot)
│ ├── foo.ext
│ ├── bar.ext
│ └── …
├── foo.md
├── bar.md
└── …
```

Motivation:

Right now the structure is a bit proprietary and I have to name the `data_directory` accordingly, like `notable`, since having it be named the most appropriate name `notes` would mean the path to actual notes would be `.../notes/notes/foo.md`, which is semantically killing everyone's OCD I'm sure :)

With the proposed simpler folder structure we could just plug any currently existing notes folder into notable without any directory tree modifications.

More semantic, and more useful.

**Comment by fabiospampinato** [comment]
I can feel the OCD-part of this, but:

> `├─┬ .attachments (note the leading dot)`

Attachments should be easily accessible from the file explorer. In most systems by default dot paths are hidden instead. Why would you want to hide this directory? If you don't use the attachments feature you could just remove the directory.

> Right now the structure is a bit proprietary

I wouldn't call it "proprietary". I think your main point is that your proposed structure could be more portable, and while that may be the case, long-term, as the product matures, if you often need to edit your notes with a separate editor it would mean that we did a poor job with the included editor.

Your other point about semantic I agree with, but IMHO storing notes in `~/.notable` or something like that isn't a big annoyance.

Keep in mind that also making any core changes like this one would require considerable efforts, as we also have to make sure that existing installations continue to work in the future. So the benefits must be significant, and I'm not seeing this.

Also the current structure has a few (minor) advantages:

- Everything is a bit more cleanly separated, there's a folder containing notes, a folder containing attachments, and the data directory could host some metadata in the future (think about git metadata #116 or custom notes order #69 or something else (per-data-directory settings perhaps?)). While you can still implement all the mentioned features when using your structure things become a bit messier if you have directory-level metadata and notes living in the same directory.

- Currently we don't re-import the tutorial notes if your data directory contains a "notes" folder already. We can't do this with your proposed structure (without keeping some extra metadata) as there's no "notes" directory. We could check if there are any markdown notes by we wouldn't be able to know if there were some notes in the past but you removed all of them.
