### ISSUE TITLE
Resizing of layout misplaces position of cursor 

### ISSUE THREAD

**Issue by HaleemDream** [fabiospampinato/notable#221]
Another bug I believe:

https://i.imgur.com/9y7ot6F.gif

Edit: Might be the same issue as #215

**Comment by fabiospampinato** [comment]
@HaleemDream It's not strictly the same issue as #215, since there you're switching focus to another application and therefore lose the cursors. Here you're basically focusing to another element within the app. Still perhaps a good enough solution could fix both issues.

**Comment by HaleemDream** [comment]
Yeah thought they could be related somehow since the issue comes from losing the cursor.

**Comment by fabiospampinato** [comment]
This turned out to be tricky, as CodeMirror stores the cursor positions by line and offset in that line rather than just the offset in the entire document. Perhaps we could convert between the two representations 🤔

**Comment by fabiospampinato** [comment]
I've partially fixed this in https://github.com/fabiospampinato/notable/commit/3982e029353f4cdc4ab0a2846003c089dc49ac0f and https://github.com/fabiospampinato/notable/commit/e7b6c14c82c635c123681cf6fda8de660451aace.

To summarize:

- The issue does not manifest itself when word wrapping is disabled (as the lines remain the same).
- If after a resize the lines actually remain the same (maybe you resized the first 2 columns) this is actually fixed now.
- If, as shown in your gif, the number of lines changes then cursors are not restored at all. Unfortunately we can't just store them as offsets from the beginning of the document as you might be editing some other lines with a separate editor and the cursors will still get misplaced again.
