### ISSUE TITLE
How to rename notes / files ?

### ISSUE THREAD

**Issue by gamato** [fabiospampinato/notable#225]
I've just realised that I don't know how to rename a note / file.

I imported a few notes (from Evernote) and one of them was just a table. And the new file and note names were set according to the first line of the table. I'd like to rename both the file as well as the title of the note. How can I do it in Notable, please?

**Comment by mnikn** [comment]
the note title is base on your level1 heading.

**Comment by fabiospampinato** [comment]
You just rename the file.

The title is inferred from the first line which contains some printable characters, if you'd like to override that just add a title to your notes, like:

```md
# My title
```

**Comment by gamato** [comment]
And do you consider this a good solution ?

When I create a new note it is nowhere suggested how the file name and note title are guessed and set. And while the current behaviour may be generic and usually okay, it clearly fails in some cases. I do not see a reason why all my notes should start with a heading of some sort. Also, it is clearly not a hard requirement as I can open the note in external editor and voila there's title in the front matter and it can be changed.

As for the file name, I'd prefer to handle my notes within one app, not to have to switch apps unnecessarily.

So why not to provide a simple way to do it, please? For instance right clicking on a note and having option(s) to rename the note and/or file.

**Comment by fabiospampinato** [comment]
> And do you consider this a good solution ?
>  I do not see a reason why all my notes should start with a heading of some sort. 

Yes. It may force people to keep their notes better organized but I don't see that necessarily as a bad thing.

Let's talk about this here #229.

> When I create a new note it is nowhere suggested how the file name and note title are guessed and set. 

It should become clear that this is the behavior the more notes you edit via Notable.

> For instance right clicking on a note and having option(s) to rename the note and/or file.

Let's talk about this here #228.
