### ISSUE TITLE
Images linked to external url do not work

### ISSUE THREAD

**Issue by titoesteves** [fabiospampinato/notable#226]
When I try to include images that link to external urls, it does not seem to work. Is this a known issue? E.g.
`![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png)`

**Comment by bendem** [comment]
Cannot reproduce, it works fine here.
<img width="1683" alt="screenshot 2019-01-07 at 13 06 04" src="https://user-images.githubusercontent.com/2681677/50767406-ffe5b680-127c-11e9-8d59-49ac230769bf.png">

**Comment by fabiospampinato** [comment]
Can't reproduce either, I guess maybe there was a problem with the internet connection or something?

**Comment by titoesteves** [comment]
@fabiospampinato can you provide the markdown you used to generate that? I am using ubuntu linux 18.04 if it helps.
