### ISSUE TITLE
Better directory structure

### ISSUE THREAD

**Issue by ad-si** [fabiospampinato/notable#230]
Hi, I just stumbled upon this project and it's funny cause I've build myself a similar setup for my notes. However, I have a different directory structure:

```txt
├── 2019-01-02t1939.md
├── 2019-01-03t1636.md
├── 2019-01-04t1912.md
├── 2019-01-07t1448
│   ├── image.png
│   └── main.md
```

The advantage is that notes and their attachments are also located next to each other on the file level. Also, I can use the filename creation timestamp to sort my notes by creation timestamp (which is my default).

If you're interested in supporting this directory style, I'd be happy to switch to notable as it's really nicely built. Otherwise I guess I'll have to keep maintaining my solution 😅.

**Comment by fabiospampinato** [comment]
I'm sorry but I like the current structure better. There's been some discussion about this: #220 #210.

**Comment by fabiospampinato** [comment]
And some more discussion here: #218 #223 #201 #54.

**Comment by ad-si** [comment]
Yeah, I saw all of this issues. They don't really explain why you don't like my proposed directory structure, but anyways, I'm not trying to convince you of anything here. Just wanted to know whether I have to keep maintaining my solution 😛.

**Comment by fabiospampinato** [comment]
@ad-si I don't like your structure because it makes it difficult to find the note I'm looking for from the file exporer (I may remember the title, what maybe not when I did create it?), it's (only? I can already sort files by creation date) advantage is that I can have multiple attachments with the same name.

> Just wanted to know whether I have to keep maintaining my solution 😛.

I guess that's mostly your choice, it would probably take less effort long-term to make a script that converts your notes directory into a format we can work with.

**Comment by ad-si** [comment]
> it makes it difficult to find the note I'm looking for from the file exporer (I may remember the title, what maybe not when I did create it?)

I always use https://github.com/BurntSushi/ripgrep to find anything, so file names are really unimportant to me. By just using the creation time stamp it's one less thing to care about. The hash of the file content would be another solution, but than the filename would have to change when changing the content which is not worth it.

> I can already sort files by creation date

Not necessarily. There is nothing like a creation time in Posix (https://unix.stackexchange.com/questions/91197/how-to-find-creation-date-of-file)
And for macOS the creation timestamp of a file is really unstable. Just move the file to an external storage and back and it's gone. Also doesn't work properly with syncing via Dropbox or Gdrive.
Futhermore it makes it more complicated to import old notes as you would have to set the creation time of the files.

> only advantage

- It makes it easier to move the note including all attachments somewhere else.
- It's easy to see how many attachments the note has
- The note + all attachments can be opened in an editor `subl 2019-01-07t1448`
- …

> it would probably take less effort long-term to make a script that converts your notes directory into a format we can work with

Maybe. However, currently the missing support for proper creation timestamp is my biggest concern.

**Comment by ad-si** [comment]
Ok, cool, looking forward to the changes.

> attachments are a bit trickier but support for properly exporting them too can be added in the future

Isn't that the whole point of notable, that I don't need an explicit import and export as everything is modeled in files 😉

> Do you often need to edit a note with its attachments with the editor though?

Yeah, I often have makefiles and scripts next to my notes in order to generate diagrams, graphics, and charts.

**Comment by fabiospampinato** [comment]
> Isn't that the whole point of notable, that I don't need an explicit import and export as everything is modeled in files 😉

I don't know if it's the _whole_ point, but it certainly is important. I'm not saying that it would be difficult to implement though, just that is not as easy a literally copying one file (the note) somewhere.

> Yeah, I often have makefiles and scripts next to my notes in order to generate diagrams, graphics, and charts for them.

We recently added support for mermaid diagrams #30. If you need anything more complicated than that maybe notable may not be the perfect choice 🤔 Perhaps when a plugins architecture #128  gets implemented this use case could be better supported.

**Comment by ad-si** [comment]
> maybe notable may not be the perfect choice

I guess not yet, but your roadmap sounds promising, so I'll definitely keep an eye on it.
Thanks for your thoughts and feedback. Keep up the great work! 😊

**Comment by fabiospampinato** [comment]
Thank you! :)
