### ISSUE TITLE
Sorting notes doesn't work

### ISSUE THREAD

**Issue by ExpLog** [fabiospampinato/notable#24]
As per the title, sorting notes in the middlebar by any field does nothing at the moment.

I've tried this with version 1.0.1, installing on Fedora using the provided snap.

**Comment by EspadaV8** [comment]
Sorting will change if you switch views. If you start on 'Notebooks', change the sort order and then click 'Tutorial' then the list will update.

**Comment by ExpLog** [comment]
You're right, selecting something on the left bar forces the middle bar to be refreshed. Still, I'd expect it to refresh as soon as I change the sorting method.

**Comment by fabiospampinato** [comment]
It should definitely work, it was working on previous builds but I must have done something that broke this.
