### ISSUE TITLE
Right click on the notebook to create note with the  right tag

### ISSUE THREAD

**Issue by synckey** [fabiospampinato/notable#250]
This is a super good app, but when I want to create note under a specific note book, I will have to set the tag to the correct one, is that possible to create the default tag for the new notes?
Thank you so much for your perfect app.

**Comment by fabiospampinato** [comment]
What version are you on? If you _left_ click a notebook and then create a note it should be properly tagged, isn't it?

**Comment by synckey** [comment]
Oh yes, you are right, if I am on the notebook and click on the `+` button, it can create note under the notebook.

I've seen that some times it will copy a note by doing the previous step, but it is tracked on #219 , feel free to close this issue. 

Thank you ~.
