### ISSUE TITLE
KaTeX spacing issues

### ISSUE THREAD

**Issue by fabiospampinato** [fabiospampinato/notable#255]
Thanks so much for this! I got inline and display formulas working in the master branch, but KaTeX seems to have spacing issues when rendering:

From the KaTeX homepage:
![image](https://user-images.githubusercontent.com/43612797/50984344-b04af900-14cf-11e9-9db0-fd3b8bdd561f.png)

From `master` branch:
![image](https://user-images.githubusercontent.com/43612797/50984383-c0fb6f00-14cf-11e9-840b-f6fe7e9d158a.png)

A few things:

- The limits on the integral are slightly too high in Notable as compared to default KaTeX
- There is no spacing around the `=` sign, between the function f and the exponential, and the `\,` between the exponential the `d\xi` seems to have been ignored completely.
- The `\hat` that's supposed to go over just `f` goes over both `f` and the opening parenthesis.

Maybe something to do with configuration settings passed to KaTeX when it's first loaded?

Code used:
```markdown
# Maths

Notable has KaTeX support. This supports both inline (\\(3x = 5\\)) and display equations:

\\[f(x) = \int_{-\infty}^\infty \hat f(\xi)\,e^{2 \pi i \xi x}\,d\xi\\]

Inline expressions: \\( e = mc^2 \\), are supported too.
```

_Originally posted by @samueldy in https://github.com/fabiospampinato/notable/issues/1#issuecomment-453174138_

**Comment by fabiospampinato** [comment]
@samueldy I've moved your comment here, I think it may be a CSS problem, we should kind of reset it for rendered SVGs.

**Comment by Ergouzii** [comment]
Hi! Just a quick comment: inline math using ```$...$``` is not working in version 1.1.0 (macOS).

**Comment by jinjie** [comment]
How do I escape dollar sign `$`? My notes not rendering correctly with dollar signs in it. I have tried escaping by `\$`. Doesn't work.

**Comment by RomanKornev** [comment]
@jinjie if you're reffering to symbols not escaping in code blocks, then #282 is for that.

**Comment by jinjie** [comment]
@RomanKornev It is not in code blocks.

It is just a simple:

`This apple cost between $1 to $2`

Rendered as 

<img width="252" alt="screenshot 2019-01-23 at 6 10 12 pm" src="https://user-images.githubusercontent.com/2721195/51599268-2886d500-1f3a-11e9-9fd6-aee54014ddbe.png">

**Comment by RomanKornev** [comment]
`This apple cost between $1$$ to $2` or
`This apple cost between $\$ $1 to $\$ $2` works for now, but I agree we should probably have a better way of doing it.

**Comment by fabiospampinato** [comment]
This is how the formula gets rendered currently (I think KaTeX kind of got updated from v0.8 to v0.10):

<img width="249" alt="screen shot 2019-01-29 at 00 57 41" src="https://user-images.githubusercontent.com/1812093/51874438-38028580-2361-11e9-8ab5-497535324b4b.png">

With AsciiMath disabled it gets rendered like this (perfect?):

<img width="266" alt="screen shot 2019-01-29 at 00 57 24" src="https://user-images.githubusercontent.com/1812093/51874451-43ee4780-2361-11e9-9071-47af0e45fa24.png">

So with AsciiMath the situation now is:

> The limits on the integral are slightly too high in Notable as compared to default KaTeX

Fixed.

> There is no spacing around the = sign, between the function f and the exponential

Fixed.

> and the \, between the exponential the d\xi seems to have been ignored completely.

This got worse.

> The \hat that's supposed to go over just f goes over both f and the opening parenthesis.

Nothing changed.

Currently AsciiMath can't be turned off, but within the next few releases I plan to add a way to set settings, that would include disabling AsciiMath.

A better solution would be if AsciiMath didn't mess the formula up, we are currently using [this](https://github.com/christianp/asciimath2tex/blob/master/asciimath2tex.js) piece of code for converting AsciiMath to TeX, perhaps it could be tweaked to better support KaTeX or something. /cc @christianp 🙏

**Comment by christianp** [comment]
You shouldn't expect that all TeX has the same meaning when interpreted as AsciiMath - it's a different language, with a different grammar. The things you've spotted are the intended behaviour of AsciiMath.

Why are you running plain TeX through the asciimath2tex?

**Comment by fabiospampinato** [comment]
@christianp I thought the two could kind of be used in the same expression without messing the output, this doesn't seem to be the case though. 

I'll switch to `$$..$$` and `$..$` for KaTeX and `~~..~~` and `~..~` for AsciiMath then.

If anyone has a better suggestion I'm all ears 👍

**Comment by fabiospampinato** [comment]
Fixed in master:

<img width="234" alt="screen shot 2019-01-29 at 16 41 37" src="https://user-images.githubusercontent.com/1812093/51920084-fb786d80-23e4-11e9-89d0-ce4d904c87b1.png">

In order to use AsciiMath the formula must be wrapped in `&&..&&` or `&..&`, I couldn't use `~~..~~` as that's already used for strikethrough.
