### ISSUE TITLE
Why package-lock.json is not committed?

### ISSUE THREAD

**Issue by sosukesuzuki** [fabiospampinato/notable#260]
Why `package-lock.json` is not committed?
I think you should commit `package-lock.json` to manage dependencies.
According to the documentation(https://github.com/npm/cli/blob/latest/doc/files/package-lock.json.md#description)

**Comment by fabiospampinato** [comment]
I don't care about what NPM says. In this situation though it's a good idea to lock the dependencies, I'll add this.
