### ISSUE TITLE
Ctrl+Z is deleting notes

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#264]
- **OS Version**: Windows 10 x64 1809
- **Notable Version**: master 0eee7e273ec9f7288590c623f44884670ede44e8

### Current behavior
1. Select note A
1. Edit something
1. Select another note B
1. <kbd>Ctrl+Z</kbd> - at this point, note B is selected with note A's content
1. <kbd>Ctrl+E</kbd> or toggle edit mode or save
1. Note B is deleted and replaced with note A contents
1. Now there are 2 note As
1. Unable to go back to the previous state at this point

### Expected behavior
Expect note B to not be deleted.
Either:
<kbd>Ctrl+Z</kbd> doesn't allow switching to previous notes
Or: 
<kbd>Ctrl+Z</kbd> also selects the previous note

**Comment by fabiospampinato** [comment]
We should reset the undo history when switching notes. Thanks for finding this bug!

**Comment by RomanKornev** [comment]
Confirmed fixed 🎉
