### ISSUE TITLE
 add tag to  a section of page

### ISSUE THREAD

**Issue by absir1949** [fabiospampinato/notable#268]
### Feature description
now the tag is add to page,  i would like it add to section。

### Feature motivation

ep:
 1.i write diary in it, everyday is a page
2. in the page, i have a section by tag : mood
3. i can see all mood section by tag view of "mood"

**Comment by fabiospampinato** [comment]
You can link to another sections of the Markdown instead #181, although this is somewhat buggy at the moment, but will be fixed soon.

**Comment by fabiospampinato** [comment]
>  I can add a tag to a part of the note

@absir1949 can you make me a screenshot or something? I'm not sure we are talking about the same thing 🤔
