### ISSUE TITLE
Connecting notes?

### ISSUE THREAD

**Issue by ozgrozer** [fabiospampinato/notable#27]
Is there any way to connect the notes to each other creating links like `<a href="/note-id">click</a>`?

**Comment by vorg** [comment]
Yes, just use `@note/filename.md` urls `[Shortcuts](@note/07 - Shortcuts.md)` as explained in the tutorial here
https://github.com/fabiospampinato/notable/blob/master/resources/tutorial/notes/10%20-%20Linking%20Attachments%E2%88%95Notes%E2%88%95Tags.md#notes

**Comment by ozgrozer** [comment]
That's amazing. It works.

**Comment by MoHD20** [comment]
Isn't it better to use more standard way to link notes? I mean shouldn't it be possible to link them using just the name? like `[Shortcuts](07 - Shortcuts.md)`

**Comment by fabiospampinato** [comment]
@MoHD20 No we need a way to distinguish between tags notes and attachments. Maybe you're never going to add a tag named `07 - Shortcuts.md` or you're never going to add an attachment named `07 - Shortcuts.md` to a note, but if you do we should support that.
