### ISSUE TITLE
Indefinitely nestable

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#271]
It seems that a lot of folks are having trouble understanding indefinitely nestable nature of tags/notebooks in Notable.

We need to update the main screenshot and tutorial structure to emphasize this feature. Just include some simple example.

**Comment by fabiospampinato** [comment]
> It seems that a lot of folks are having trouble understanding indefinitely nestable nature of tags/notebooks in Notable.

Yeah I've noticed this too.

> We need to update the main screenshot and tutorial structure to emphasize this feature. Just include some simple example.

I don't know I don't want to overcomplicate the tutorial notes just for this. Maybe I could prompt the reader to add the `foo/bar/baz` tag themselves in the tutorial note about tags? 🤔

**Comment by RomanKornev** [comment]
Maybe add another screenshot to Demo section of Readme?

**Comment by RomanKornev** [comment]
Looks good!
