### ISSUE TITLE
Fullscreen note

### ISSUE THREAD

**Issue by mnikn** [fabiospampinato/notable#272]
### Feature description

Is it possible to fullscreen the note? I think maybe it can work with [#Split-view editing/previewing](https://github.com/fabiospampinato/notable/issues/77).

### Feature motivation

Sometimes we want to focus on a single note, so fullscreen a note would be better.

**Comment by fabiospampinato** [comment]
@mnikn Maybe we could add support for it. Isn't focus mode good enough?

**Comment by mnikn** [comment]
@fabiospampinato I'm not sure what is the focus mode, do you mean open in default app? 

Yes open the file by our own markdown editor can do it, but I'm not sure it's a good idea or not, it depend on what kind of problems should notable handle. Does it only focus on note management, or it can also handle the note edit?

**Comment by mnikn** [comment]
Sorry I didn't know it before, it looks nice right now. Maybe it will be better to put the focus button in mainbar-toolbar.

**Comment by fabiospampinato** [comment]
Nah, the less buttons the better. Not everyone uses focus mode and those who do should learn the shortcut.

**Comment by bendem** [comment]
> Nah, the less buttons the better. Not everyone uses focus mode and those who do should learn the shortcut.

It's the second time I read this. Why not make the toolbar customizable like in most software?

![screenshot 2019-01-14 at 16 16 39](https://user-images.githubusercontent.com/2681677/51121468-d518d680-1817-11e9-99ee-1ec89d1be4c2.png)
![screenshot 2019-01-14 at 16 16 22](https://user-images.githubusercontent.com/2681677/51121469-d5b16d00-1817-11e9-8b02-a3c58a8a96b2.png)

**Comment by fabiospampinato** [comment]
@bendem everything will be pretty customizable once I add support for plugins #128.

The toolbar customization on your first screenshot is for native macos apps, so we can't use that. We could develop something custom like shown in the second screenshot, but that will take some considerable time that at this early stages I'd rather spend on other issues.

**Comment by fabiospampinato** [comment]
I'm closing this as Focus Mode seems to suffice.
