### ISSUE TITLE
Grayed out checkboxes 

### ISSUE THREAD

**Issue by Trenar** [fabiospampinato/notable#274]
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.1.0

### Current behavior

In my notes, the checkboxes created by `- [ ]` and `- [x]` are very hard to see. They seem to have a high alpha value. 
![screenshot from 2019-01-14 13-20-59](https://user-images.githubusercontent.com/31891152/51112551-46985b00-17ff-11e9-8169-aa8261d7fe45.png)

I don't know if this is only related to Ubuntu or something else, has anyone the same experience?

### Expected behavior

More visible checkboxes like in the screenshot of #169 .

**Comment by fabiospampinato** [comment]
Maybe I can make them more visible, but fixing #169 would also fix this.
