### ISSUE TITLE
Tags shouldn't be evaluated inside code

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#282]
- **OS Version**: Windows 10 x64
- **Notable Version**: master b4ad988882acf51838b85b995770269a64d5abac

### Current behavior
Some strange things are happening with tags in code blocks:
Special symbols are displayed as escaped characters.

```plaintext
(@tag/$1) - displays correctly
[](@tag/$1) - displays incorrectly as [](@tag/%C2%A8D1) in preview
"[](@tag/$1)" - displays incorrectly
```
```
`[](@tag/$1)` - also displays incorrectly
```

### Expected behavior

Expect `[](@tag/$1)` to be displayed as `[](@tag/$1)` inside code.

**Comment by fabiospampinato** [comment]
Those special urls are escaped, or they won't work. Does clicking on the generated button works?

**Comment by RomanKornev** [comment]
It doesn't have a button. It's inside a code block.
![tags-in-code](https://user-images.githubusercontent.com/5807561/51265144-26b49300-19c9-11e9-8b22-2a41914ab3bf.png)
I want to display the underlying markdown as actual code, not a button.
My theme has nothing to do with it btw. Confirmed in master branch as well.

**Comment by fabiospampinato** [comment]
Right, this is an issue I also stumbled upon when writing the tutorial notes. I'm afraid detecting if we are inside a code block from showdown is not that simple 🤔.

**Comment by fabiospampinato** [comment]
This is fixed in the master branch.
