### ISSUE TITLE
Main menu displayed, but unreadable with Ubuntu 18.10

### ISSUE THREAD

**Issue by jonrandy** [fabiospampinato/notable#289]
- Ubuntu 18.10
- 1.10

### Current behavior

Launch Notable in Ubuntu 18.10 with default Ubuntu theme 'Naru'. Main menu text colour is indistinguishable from the background. This is a problem with Electron - see https://github.com/ubuntu/yaru/issues/969

When the app loses focus, the menu becomes readable.

### Expected behavior

Menu should be readable when app focused

![screenshot from 2019-01-17 09-17-02](https://user-images.githubusercontent.com/1510194/51291206-f4db1500-1a38-11e9-8177-cd289adf74c8.png)

![image](https://user-images.githubusercontent.com/1510194/51291313-3d92ce00-1a39-11e9-8546-41adc14c26cc.png)

**Comment by jonrandy** [comment]
I think that should work

**Comment by fabiospampinato** [comment]
I've recently upgraded electron to v4.0.2 and I'm going to publish a new release soon, @jonrandy let me know if that fixed the issue for you.

**Comment by jonrandy** [comment]
Yes, it is now fixed in 1.2!
