### ISSUE TITLE
README missing instructions to install/run from *user* perspective

### ISSUE THREAD

**Issue by zachvalenta** [fabiospampinato/notable#29]
*disclaimer: I'm not very familiar w/ JS or Electron, so maybe I'm missing something obvious*

Instructions to run the app are oriented towards contributors, but given that Notable has a major version I'd expect something in the `README` on how to install/run the app from the perspective of a *user*. 

I tried to get the app up and running following the `Contributor` guidelines and couldn't do so.

Btw, the app looks awesome, can't wait to use, I've been using a home-rolled note-taking system (Markdown, Sublime) and look forward to trying out something new!

**Comment by matejdro** [comment]
Not sure on what platform you are, but for Windows I just downloaded the .exe from [Releases](https://github.com/fabiospampinato/notable/releases) page and double clicked it.

**Comment by zachvalenta** [comment]
doh! just realized I downloaded the wrong executable

cheers @matejdro
