### ISSUE TITLE
Application menu not available in Windows

### ISSUE THREAD

**Issue by Atticus-** [fabiospampinato/notable#3]
When using Notable on Windows, the application menu is not present at the top of the window.

![missingmenuwindows](https://user-images.githubusercontent.com/1552841/50462557-f1bd9f00-093a-11e9-84c2-d15772997e5a.PNG)

**Comment by fabiospampinato** [comment]
It's actually there, but you have to press `Alt` to show it. Isn't this a common-enough practice on Windows? 🤔 Perhaps I should just make it visible all the time, or at least mention this in the readme/tutorial.

**Comment by Atticus-** [comment]
Alt usually focuses the menu, I don't think I've ever seen it used to show a hidden menu. Definitely Windows users would feel more comfortable with it shown all the time (although a configurable setting never hurts).

I didn't even know a menu existed until I saw it mentioned in "The Data Directory" -- you might add a side note about Windows there if you wanna keep it hidden. Feel free to close if you're fine with the existing behavior.

**Comment by Phlosioneer** [comment]
I would very much appreciate mentioning in the tutorial that alt shows/hides the menu bar. It's a very strange behavior I've never seen before.

**Comment by RomanKornev** [comment]
Perhaps integrating it into the title bar like VSCode would be the best solution:
<img alt="notable_bar" src="https://user-images.githubusercontent.com/5807561/50515908-8e597b80-0ab8-11e9-95d2-f126d0aa78f5.png">

**Comment by fabiospampinato** [comment]
> Perhaps integrating it into the title bar like VSCode would be the best solution:

Probably, but I think they wrote the menu widget themselves, I would rather not go that route.
