### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by apisarenco** [fabiospampinato/notable#30]
[Mermaid charts](https://github.com/knsv/mermaid) are present in such editors as Typora and Boostnote, as well as available online in places like [StackEdit](https://stackedit.io).
Since a picture is worth a thousand words, it would be good to have support for it.

**Comment by fabiospampinato** [comment]
If there's a [showdown](https://github.com/showdownjs/showdown) plugin for this it could be added easily.

**Comment by mschmid** [comment]
This was a great improvement in value for me, thanks!

**Comment by bendem** [comment]
Awesome idea, love the feature!
