### ISSUE TITLE
Export icon font

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#304]
- **OS Version**: Windows 10 x64
- **Notable Version**: master baf40491739761b331907a7cbb92b8b0cac04967

### Current behavior

After exporting a note to HTML or PDF, the icons are replaced with text that cuts off.
![2019-1-19 16-18-36](https://user-images.githubusercontent.com/5807561/51427186-e9891480-1c05-11e9-9cbf-736eaf728d63.png)
![2019-1-19 16-19-17](https://user-images.githubusercontent.com/5807561/51427199-0d4c5a80-1c06-11e9-91c1-3cb3325b9e82.png)

### Expected behavior

Export `font_icons` as well:
![image](https://user-images.githubusercontent.com/5807561/51427249-bd21c800-1c06-11e9-9f76-eb3a0d024e9a.png)

**Comment by fabiospampinato** [comment]
Icons are now removed properly, integrating the icon font would be tricky, and I'm not sure if it would be that important.
