### ISSUE TITLE
Push notable...snap to snapcraft.io store

### ISSUE THREAD

**Issue by frodo8847** [fabiospampinato/notable#305]
I downloaded the notable***.snap and then found that
to install it I had to use the --dangerous flag:
 
sudo snap install --dangerous notable***.snap

command. Without the flag I get an error msg about lack
of signatures/metadata which was unexpected and rather distressing.
Putting the *.snap in their store eliminates this problem and
can be used to push update notifications to users of the store.

**Comment by fabiospampinato** [comment]
Duplicate of #98
