### ISSUE TITLE
Let sidebars be collapsable 

### ISSUE THREAD

**Issue by HaleemDream** [fabiospampinato/notable#306]
### Feature description
Let the sidebars be collapsible. 

### Feature motivation
Generally when I open notable, it seems like the sidebars are taking up too much space and I'm always making the width as small as possible. Would be nice if I just collapse them and let the notes section take up most of the space.

https://imgur.com/a/GGEUlOR

**Comment by fabiospampinato** [comment]
Just enable "focus mode" from View -> Toggle Focus Mode.
