### ISSUE TITLE
Asterix causes bolding inside fix-width block

### ISSUE THREAD

**Issue by nikodemus** [fabiospampinato/notable#31]
Example:

    a*b

renders as shown in the image. This should not occur, as seen eg. above.

![image](https://user-images.githubusercontent.com/153172/50482758-f47acb80-09f0-11e9-84aa-179f49e0d49e.png)

**Comment by fabiospampinato** [comment]
Can you post a whole note that reproduces this? For me `a*b` get rendered correctly in preview mode, and the `*b` characters get rendered in italic in editing mode.

**Comment by fabiospampinato** [comment]
Closing since I can't reproduce and no more info has been provided.

**Comment by nikodemus** [comment]
Test

```
a*b
```

**Comment by nikodemus** [comment]
Yeah, this is gone now. Thank you anonymous fixer of things!
