### ISSUE TITLE
Cannot select text in split-view

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#314]
- **OS Version**: Windows 10 x64 1809
- **Notable Version**: master 6710d63c469da71112c14609998ba4a67e8a6b42

### Current behavior

Cannot select text in split-view like in regular preview. Cursor doesn't change as well.

**Comment by fabiospampinato** [comment]
@RomanKornev Is the cursor stuck in the "resize columns" icon?

**Comment by RomanKornev** [comment]
No, it's just a regular cursor. It changes when I hover over a link but that's it. Everything works on the left Edit window, but not on the right Preview window.

**Comment by fabiospampinato** [comment]
Sounds like a bug, thanks for reporting it 👍
