### ISSUE TITLE
Listing notes under a tag

### ISSUE THREAD

**Issue by bendem** [fabiospampinato/notable#319]
### Feature description

A special syntax that would include the notes available under a tag in the current note.
The following syntax is just to show what I mean, not a request to support custom xml tags in markdown.
```xml
<list-notes tag="life/food" recursive="true" sort="updated:desc" excerpt="true" limit="15" />
```

The excerpt part is somewhat related to #244 as it allows finding information more quickly without having to open every note. It's probably better tracked there.

### Feature motivation

I use notes as a personal wiki and having meta notes linking to the recent notes in a subtag is a nice feature. Currently, I do that by creating a note named `000-index` in the parent tag and listing notes. But it's annoying, error prone and something that could be easily automated.

**Comment by fabiospampinato** [comment]
Sounds like a good application for plugins, in the future there should be plugins that are able to insert content inside a rendered note, perhaps you would "call" them by inserting a special html tag inside the note or something along those lines, then the plugin will handle the logic. Let's track this here #128
