### ISSUE TITLE
Renaming attachment on Windows removes the attachment

### ISSUE THREAD

**Issue by matejdro** [fabiospampinato/notable#32]
Not sure if I'm doing something wrong, but when I try to use Rename option in Notable, I will get greeted with this message:

`Simply rename the actual attachment file while Notable is open`

Okay, then I go into the `attachments` folder and rename the file. But doing that removes thee attachment from the note's attachment list, it does not rename it.

**Comment by bluehash** [comment]
I can replicate it on 1.0.1

Environment: Win 7, 64-bit.

**Comment by fabiospampinato** [comment]
I think either renames are not detected under Windows, which won't be easy to fix, or this issue is somehow caused by different tools returning different file path formats 🤔

**Comment by matejdro** [comment]
As a workaround, you could implement actual rename inside the app if windows renames cannot be detected.

**Comment by fabiospampinato** [comment]
The problem is that under Windows we don't detect properly when a file gets renamed, I'll work on that.

> As a workaround, you could implement actual rename inside the app if windows renames cannot be detected.

We still want to properly detect renamed files though, so I'd rather fix the problem first.

**Comment by Trenar** [comment]
see #265

**Comment by fabiospampinato** [comment]
Should be fixed now, it turns out that when renaming on macOS the "unlink" event is emitted before the "add" event, on Windows is the opposite.
