### ISSUE TITLE
Front-matter blocks title inference

### ISSUE THREAD

**Issue by c-kirkeby** [fabiospampinato/notable#324]
- **OS Version**: Windows 10
- **Notable Version**: v1.1.0

### Current behavior
Currently adding front-matter to the top of a note causes the note to be 'Untitled'. As you can see in my screenshot below I've got the first heading 'Regression Testing' but it's under the front-matter.
![image](https://user-images.githubusercontent.com/820173/51580599-cb2a5e00-1f10-11e9-84c3-e8a3cd299043.png)

I added the following markdown to make this happen:

```
---
title: Regression Testing
date: 23/01/2019
---

# Regression Testing
```

### Expected behavior

While I understand that front-matter isn't documented anywhere (to my knowledge), it seems to currently work, allowing you to add metadata that doesn't get rendered in the document view. It would be cool if it could still infer the title or derive the title from the front-matter (which I believe there's some discussion about in other tickets).

**Comment by fabiospampinato** [comment]
@c-kirkeby you can't edit the font-matter like that, you'll have to open the entire note in a separate editor and edit it there. Then the title will be updated.

**Comment by c-kirkeby** [comment]
It's useful to be able to add your own metadata, especially when authoring pages for [gatsby](https://github.com/gatsbyjs/gatsby). In particular, I'm not too fussed about editing the title, but the date is a useful metadata to be able to add myself without needing to put it into the rendered markdown in every document.

**Comment by fabiospampinato** [comment]
@c-kirkeby what "date" are you talking about exactly? Related issue: https://github.com/fabiospampinato/notable/issues/67

**Comment by c-kirkeby** [comment]
@fabiospampinato Custom front-matter that I added myself. I didn't edit any existing front-matter, I added the block below to a new note from within Notable:
```markdown
---
title: Regression Testing
date: 23/01/2019
---
```

If that's not supported then that's fine, but it does make Notable unsuitable for some tasks in that case.

**Comment by fabiospampinato** [comment]
We are not going to support 2 frontmatters, that would be weird.

**Comment by c-kirkeby** [comment]
As an alternative solution I've tried to add HTML comments to the top of the document, but it still causes the document to be 'Untitled':

```markdown
<!--
  date: 23/01/2019
-->
# Regression Testing
```

**Comment by fabiospampinato** [comment]
Yes because the first non-empty non-all-whitespace line is `<!--`.

IMHO your use case is basically a duplicate of #67, as you want additional customizable metadata within the app.
