### ISSUE TITLE
Add setting for default notebook

### ISSUE THREAD

**Issue by amelandri** [fabiospampinato/notable#326]
### Feature description

Add an option to define the default notebook presented to the user when the app opens

### Feature motivation

The user would be able to create and quickly use an Inbox notebook, instead of being presented the All Notes view.

I don't know if this is feasible since Notebooks usage is not mandatory in Notable

**Comment by fabiospampinato** [comment]
I think it would be better to restore the active tag across restarts, would that work for you @amelandri ?

**Comment by amelandri** [comment]
Indeed it would work.

**Comment by fabiospampinato** [comment]
Closing in favor of the more general #339.
