### ISSUE TITLE
Prosemirror

### ISSUE THREAD

**Issue by jcuenod** [fabiospampinato/notable#345]
Have you considered using `prosemirror` instead of `codemirror` for the editor? This might reduce the differentiation between the edit and non-edit modes. As far as I know, it's by the same people so it may not be difficult to swap in: https://prosemirror.net/

**Comment by RomanKornev** [comment]
We are switching from CodeMirror to Monaco #203.

**Comment by fabiospampinato** [comment]
> Have you considered using prosemirror instead of codemirror for the editor? 

No, I've never actually heard of prosemirror and I don't want to edit my notes via a WYSIWYG editor. Plus as @RomanKornev mentioned we'll replace CodeMirror with Monaco.
