### ISSUE TITLE
Windows shortcut for 'New from Template' does not work

### ISSUE THREAD

**Issue by amelandri** [fabiospampinato/notable#347]
- **Windows 10**:
- **Versione 1.2**:

### Current behavior

The shortcut <kbd>Cmd+Alt+Shift+N</kbd> - New from Template does not work.

I tried all the combinations (<kbd>Ctrl+Alt+Shift+N</kbd>, <kbd>Win+Alt+Shift+N</kbd>, <kbd>Win+Ctrl+Shift+N</kbd>) but I cant get it to work.

**Comment by fabiospampinato** [comment]
The shortcut for Windows should be `Ctrl+Alt+Shift+N`, I'll look into this.

**Comment by fabiospampinato** [comment]
It works for me, are you sure you're executing the command when a template is active?

**Comment by fabiospampinato** [comment]
> But, what's the point of having a shortcut like this if I need to select the template with the mouse?

You don't have to select the template with the mouse. Even if you did this shortcut would save you another mouse interaction.

> I'm used to Atlassian Confluence template management and I think it works pretty well. What do you think?

It seems reasonable, maybe we could have something like that in the future.
