### ISSUE TITLE
Improve auto-updater

### ISSUE THREAD

**Issue by fabiospampinato** [fabiospampinato/notable#350]
### Feature description

- [x] The auto-updater should check every day if there's a new update.
- [x] There should be a button for checking manually if there's an update.
- [x] It should be disableable, so that people on a limited connection can choose not to download the update.

**Comment by yougotwill** [comment]
Hi @fabiospampinato just wondering why the issue was closed?

**Comment by fabiospampinato** [comment]
@yougotwill because I've implement it. But the setting isn't configurable yet.

**Comment by yougotwill** [comment]
@fabiospampinato Ok cool. Didn't see any related commits so just wanted to follow up. Thanks for the hard work :)

**Comment by fabiospampinato** [comment]
Yeah I hadn't pushed them here yet.
