### ISSUE TITLE
Part of a note bleeding into another

### ISSUE THREAD

**Issue by Fastidious** [fabiospampinato/notable#351]
- **OS Version**: macOS 10.14.2
- **Notable Version**: 1.2.0

### Current behaviour

Edit note `07 - Shortcuts`, scroll to bottom. Still on editing mode, click on note `08 - Importing`, see bottom of that note. You will see the last line of the previous note in it.

### Expected behaviour

The above should not occur.

**Comment by fabiospampinato** [comment]
Duplicate of #160
