### ISSUE TITLE
Mac app does not quit after ⌘Q

### ISSUE THREAD

**Issue by glowacky** [fabiospampinato/notable#354]
- **OS Version**: MacOS 10.14.2
- **Notable Version**: 1.2.0

### Current behavior

Whether using ⌘Q shortcut or selecting "Quit Notable" in the menu bar, Notable remains open and in dock.

### Expected behavior

Notable processes should end after user selects "Quit Notable" from menu or uses ⌘Q shortcut.

Thanks for making a great app!

**Comment by fabiospampinato** [comment]
Good catch!
