### ISSUE TITLE
Improve search results navigation

### ISSUE THREAD

**Issue by amelandri** [fabiospampinato/notable#358]
### Feature description

When viewing search results, it could be useful to highlight Notebooks and Tags that contains notes included in results.

There should be also a Clear search results button.

### Feature motivation

Currently, when viewing search results a user can click on Notebooks or Tags to filter results, but there's no way to know which Notebooks or tag contain search results.
Also, if the user click on a Notebook that does not contain search results, nothing happens.

**Comment by fabiospampinato** [comment]
> When viewing search results, it could be useful to highlight Notebooks and Tags that contains notes included in results.

I think this would look pretty weird, as you still don't know which note belongs to what tag. I don't think this will be particularly useful, also as soon as advanced search operators #293 get implemented the need for this should decrease.

> There should be also a Clear search results button.

Let's track this here #360.

> Currently, when viewing search results a user can click on Notebooks or Tags to filter results, but there's no way to know which Notebooks or tag contain search results.

🤔 We could update the counters next to the tags, this would be a pretty clean implementation. But it would slow things down as now all notes needs to be searched, always.

> Also, if the user click on a Notebook that does not contain search results, nothing happens.

This sounds like a bug, can you paste the content of a note that is returned as a search result but you think it shouldn't? This will also improve once we improve the algorithm #340.

**Comment by amelandri** [comment]
I think you are right. Probably it would be confusing highlighting elements in the sidebar. 

Another solution could be changing the search results layout and add a subtle indication of related notebooks/tags.

**Comment by amelandri** [comment]
> > Also, if the user click on a Notebook that does not contain search results, nothing happens.
> 
> This sounds like a bug, can you paste the content of a note that is returned as a search result but you think it shouldn't? This will also improve once we improve the algorithm #340.

I think there's a misunderstanding. Take a look at the gif below. When you are viewing search results and click on a notebook that does not contain any reusult, nothing happens.

![search](https://user-images.githubusercontent.com/140700/51801402-6b4bf400-223d-11e9-8249-1f00390e49aa.gif)

**Comment by fabiospampinato** [comment]
> I think there's a misunderstanding. Take a look at the gif below. When you are viewing search results and click on a notebook that does not contain any reusult, nothing happens.

That definitely looks like a bug, thanks for reporting it 👍

**Comment by fabiospampinato** [comment]
> 🤔 We could update the counters next to the tags, this would be a pretty clean implementation. But it would slow things down as now all notes needs to be searched, always.

I've opened a separate issue for this here https://github.com/fabiospampinato/notable/issues/366
