### ISSUE TITLE
Allow note editing in focus mode

### ISSUE THREAD

**Issue by lukaskawerau** [fabiospampinato/notable#359]
### Feature description

Currently, editing a note in focus mode is not possible: you can only edit a note in full view (three panels) or in focus-split-mode. Ideally, users should also be able to edit a note in normal focus mode.

### Feature motivation

It's very confusing that the edit button (or any other button) does not work when in focus mode.  
When I want to do focused writing, I would like to be able to focus on only one note and only see that note, even without a preview of what I'm writing looks like when rendered.

**Comment by fabiospampinato** [comment]
> It's very confusing that the edit button (or any other button) does not work when in focus mode.

They work for me, it sounds like a duplicate of #133 ?

**Comment by RomanKornev** [comment]
@lukaskawerau Does Ctrl+E to toggle editing work for you?

**Comment by lukaskawerau** [comment]
Very weird, now I can't reproduce it anymore...  
Maybe restarting Notable 5x did the trick, oh well.

**Comment by fabiospampinato** [comment]
@lukaskawerau are you under macOS?

**Comment by lukaskawerau** [comment]
yes, 10.14.1
