### ISSUE TITLE
Add Undo/Redo menu item

### ISSUE THREAD

**Issue by pakLebah** [fabiospampinato/notable#37]
I know this sounds trivial, but some people prefer to have the `Undo` and `Redo` submenu items in the `Edit` menu. I know the shortcuts (`cmd+z` and `cmd+shift+z`) do work, but it's more satisfying to see them on the application's menu as well.

Thank you.

**Comment by fabiospampinato** [comment]
Agree, the apps would probably feel more native with those.

I don't remember why I didn't include them though, maybe I thought they could create some confusion as users may thing that actions liks favoriting/pinning a note are undoable that way 🤔
