### ISSUE TITLE
Ability to minimize sidebars

### ISSUE THREAD

**Issue by jwlodek** [fabiospampinato/notable#371]
### Feature description

The ability to minimize the two sidebars in Notable (the note list and the notebook etc. list)

### Feature motivation

When I am writing notes I don't necessarily need to see a list of other notes, so I think some sort of toggle would be nice. Something similar to how sidebars are handled in Visual Studio would be great

**Comment by fabiospampinato** [comment]
> Something similar to how sidebars are handled in Visual Studio would be great

Please elaborate.

Right now we have focus mode (view ->toggle focus mode) and the columns are resizable, I think that's enough for most use cases.

**Comment by jwlodek** [comment]
Ah I didn't see focus mode! That does exactly what I needed thanks for a great editor!
