### ISSUE TITLE
Crash on directory change

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#372]
- **OS Version**: Win10
- **Notable Version**: c8034be99d17f5d298a38fce31edbb34a230970d

### Current behavior

Commit c8034be99d17f5d298a38fce31edbb34a230970d broke the directory change.
It now crashes every time I change a directory.
Upon reload, the directory is changed.

### Expected behavior

Not crashing.

**Comment by fabiospampinato** [comment]
Thanks for the bug report, very useful!
