### ISSUE TITLE
How to open Notable using terminal?

### ISSUE THREAD

**Issue by akhilesh-k** [fabiospampinato/notable#375]
How do I open Notable using terminal? Also other directories are not accessible.

**Comment by fabiospampinato** [comment]
> How do I open Notable using terminal?

I don't know, I can do a `open /Applications/Notable.app` on my system.

> Also other directories are not accessible.

Can you elaborate? What steps are you taking and what's the result?

**Comment by amelandri** [comment]
In windows cmd:

C:\Users\USERNAME\AppData\Local\Programs\notable\Notable.exe

**Comment by jwlodek** [comment]
For powershell, add the following to your powershell profile:
```
Set-Alias notable PATH_TO_NOTABLE.exe
```
Then typing 'notable' will run the program. You can do the same thing on linux by editing a similar command in ~/.bashrc

**Comment by akhilesh-k** [comment]
> > How do I open Notable using terminal?
> 
> I don't know, I can do a `open /Applications/Notable.app` on my system.
> 
> > Also other directories are not accessible.
> 
> Can you elaborate? What steps are you taking and what's the result?

Thanks! Helped.
