### ISSUE TITLE
Allow selecting recent data directories

### ISSUE THREAD

**Issue by jwlodek** [fabiospampinato/notable#376]
### Feature description

Add option of selecting recent data directories

### Feature motivation

I've been using Notable for taking notes for school, and I like to keep separate directories for each of my classes. Because of this, I've made a data directory for each class, and have been switching between them. It would be nice to be able to go to file and then have an option 'Open Recent' that opens a list of recently opened data directories

**Comment by fabiospampinato** [comment]
Definitely, let's track this here: https://github.com/fabiospampinato/notable/issues/338
