### ISSUE TITLE
HTML evaluation inside code blocks

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#377]
- **OS Version**: Win10
- **Notable Version**: f448fc44cf769037440a488c3d0c8783cf1300e5

### Current behavior

It seems like the new markdown rendering in code blocks in preview mode still has some problems.
Putting any valid HTML code immediately evaluates it instead of displaying it raw like it was previously in v1.2.0.
![image](https://user-images.githubusercontent.com/5807561/51942049-284d7480-2427-11e9-8cae-80dbd338d9bb.png)

    ```
    <strong>bold</strong>
    ```
becomes **`bold`**, instead of `<strong>bold</strong>`

### Expected behavior

Don't evaluate html inside code.
If no language was specified, it should just display as unstyled text.

**Comment by fabiospampinato** [comment]
My bad, thanks!
