### ISSUE TITLE
import gists

### ISSUE THREAD

**Issue by k1nghat** [fabiospampinato/notable#395]
### Feature description
import gists from github.
### Feature motivation
there are probably a bunch of people who already have a trove of gists already built up.

**Comment by Fastidious** [comment]
A gist can be anything, not necessarily an `.md` document. Each `gist` is also a `git` repository, they are not simply files in a directory. I really can fathom a way to do what you are asking. Maybe you want [Lepton](https://hackjutsu.com/Lepton/)?

**Comment by fabiospampinato** [comment]
Yeah @Fastidious suggestion seems appropriate.

**Comment by k1nghat** [comment]
> A gist can be anything, not necessarily an `.md` document. Each `gist` is also a `git` repository, they are not simply files in a directory. I really can fathom a way to do what you are asking. Maybe you want [Lepton](https://hackjutsu.com/Lepton/)?

almost nothing thats imported to notable would be an md doc. gists are still just text. you auth with GH and pull the texts. i got the idea from lepton. lepton is pretty slow and i dont really want to store my notes in gists.

**Comment by Fastidious** [comment]
@k1nghat copy and paste works. 😛

**Comment by k1nghat** [comment]
> @k1nghat copy and paste works.

you can literally make the same case for all importers.
