### ISSUE TITLE
Feature Request: Create new notes from search by hitting enter

### ISSUE THREAD

**Issue by kergoth** [fabiospampinato/notable#40]
In Notational Velocity, there's a nice feature where if you input text in the search field that gives no search results, if you hit enter, it'll create a note with the search text as the title (IIRC it selects the first result if you hit enter with results). It's pretty convenient, so it'd be nice to see it here as well.

**Comment by fabiospampinato** [comment]
I'm not sure I understand the exact use case for this, I guess it would be useful when you want to create a note unless it exists already, but can you give me a practical example of this?

**Comment by kergoth** [comment]
That's the use case, yes, creating if it's not already there in some form, avoiding duplication when you have hundreds or even thousands of notes. Start typing a note title, and simultaneously search for an existing note and then quickly create a new one using the search text as the default note title rather than 'Untitled'. It's a convenience, rather than having to hit +, click on the right spot, delete Untitled, and input the title, possibly a second time.

Basically I'm proposing two new behavioral tweaks:
- Pre-fill the new note title from the search text rather than "Untitled". This could be done on its own,  or in addition to the next proposed change:
- Create a new note if you hit enter in the search box with no results, rather than, say, selecting the first result

I don't think either would cause much difficulty for users expecting the current behavior, as I doubt many feel the need to hit enter after a search anyway, given it's search-as-you-type, and if the default title is wrong from the search text, they'd have to remove it just like they'd have to replace Untitled anyway.

**Comment by kergoth** [comment]
Thanks! I'm loving the app so far, it meets a real need.

**Comment by fabiospampinato** [comment]
@kergoth I'm glad to hear that :) The amount of interest on Notable has totally amazed me. I thought that probably most people, especially those who know Markdown, had their note-taking needs already taken care of, but it looks like that's not the case.
