### ISSUE TITLE
Line Breaks/Text Wrapping not working

### ISSUE THREAD

**Issue by cutterkom** [fabiospampinato/notable#400]
- **OS Version**: 10.14.2 
- **Notable Version**: 1.2.0

### Current behavior

Word Wrapping is not working in the editing mode: 
<img width="514" alt="grafik" src="https://user-images.githubusercontent.com/4574033/52122108-1daaff00-2622-11e9-8864-0fdaf67890d4.png">

This was working at the beginning. I suspect, I was using some weird shortcut. But unfortunately Google can't help with anything useful. 

Do you have an idea?

### Expected behavior

Text wraps automatically when "touching" the end of the line.

**Comment by RomanKornev** [comment]
Use <kbd>Alt-Z</kbd> - Toggle line wrapping.
We should probably add it to the menu bar.

**Comment by cutterkom** [comment]
Thanks a lot! 

Notable is really great. Perfect match for working with synced files via ownload, nextcloud etc.

**Comment by fabiospampinato** [comment]
@cutterkom btw you're running an outdated version of the app, you should quit it (not just close the window) and re-open it.
