### ISSUE TITLE
Nested Notes

### ISSUE THREAD

**Issue by ssebs** [fabiospampinato/notable#417]
### Have nested notes based on the file tree

e.g. 

```
.
|-- school
|   |-- cs
|   |   |-- sample2.md
|   |   |-- sample3.md
|   |   `-- sample.md
|   |-- english
|   |   `-- sample.md
|   |-- math
|   |   `-- sample.md
|   `-- sample.md
`-- work
    |-- meeting
    |   |-- 20190121
    |   |   `-- sample.md
    |   |-- 20190201
    |   |   `-- sample.md
    |   `-- sample.md
    |-- projects
    |   |-- main.md
    |   `-- secondary.md
    |-- resume
    |   `-- v1.md
    `-- sample.md

```

Currently have a bunch of docs in a git repo, which have files separated by multiple folders. It would be nice to be able to view all the notes in their existing location without tagging everything.

**Comment by fabiospampinato** [comment]
I think this is out of scope. Notable uses tags for organization, and you can't achieve the same things with just folders (see #220 #210 #54 etc.), if you want to use folders instead you should probably use Typora or vscode or something.

**Comment by PHHENS** [comment]
Dear Fabio,
Tree hierarchy and tags are not opposite, but complementary functionalities  ...
Thanks for understanding this
