### ISSUE TITLE
Run Notable as a web service (instead of electron)

### ISSUE THREAD

**Issue by jkaberg** [fabiospampinato/notable#419]
I did try to search a few keywords, nothing related seem to come up.

### Feature description
I'd like to be able to run notable as a service on a web server (eg. in a docker container with a reverse proxy in front). Authentication could be optional for me, as I will let the proxy handle it.

### Feature motivation
This way I don't need to setup synchronization, install apps on various devices etc.

**Comment by fabiospampinato** [comment]
The closest issue to this one might be #83.

What you want is a self-hostable server. I'm planning on developing a web-app and related server infrastructure, but that won't probably be open-sourced, as I need Notable to be [profitable](https://github.com/fabiospampinato/notable/issues/353).

**Comment by jkaberg** [comment]
Didn't think PWA (https://developers.google.com/web/progressive-web-apps/) was the same thing as what I mentioned, but that will do fine by me

**Comment by fabiospampinato** [comment]
@jkaberg yes your issue is more about being able to self-host the whole thing. I've linked the other issue just so that you can keep track of progress in that front.

**Comment by fghhfg** [comment]
+1 for self-host web service!

I'm not a dev, but...
convert to web service, then wrap the whole thing for desktop app maybe easier... ?
of course you will lost some features if you do that.

my 2 cents
