### ISSUE TITLE
Some navigation keyboard shortcuts don't work on Windows

### ISSUE THREAD

**Issue by twwilliams** [fabiospampinato/notable#42]
The shortcuts note in the Tutorial suggests replacing Ctrl with Alt on Windows. However, that doesn't work in all cases:

- **Ctrl+Alt+Shift+Tab:** This is a Windows shortcut and overrides Notable
- **Ctl+Alt+Tab:** This is a Windows shortcut and overrides Notable

**Comment by twwilliams** [comment]
I must not have been clear. There are no working keyboard shortcuts on Windows that will go to the previous or next tag since the shortcuts are already owned by Windows.

Substituting Alt for Ctrl doesn't work in these cases, either.

I suggest using Ctrl+Page Down and Ctrl+Page Up on Windows since those are common shortcuts for this kind of functionality.

**Comment by fabiospampinato** [comment]
@twwilliams Thanks for the clarification and the suggestion, I'll have this fixed in the next release.

**Comment by fabiospampinato** [comment]
Added some more shortcuts:

- <kbd>Ctrl+Alt+PageUp</kbd> - Previous tag.
- <kbd>Ctrl+Alt+PageDown</kbd> - Next tag.
- <kbd>Ctrl+PageUp</kbd> - Previous note.
- <kbd>Ctrl+PageDown</kbd> - Next note.

**Comment by sergeevabc** [comment]
Err… Why don’t simple Top and Bottom arrows switch Previous and Next notes?

**Comment by fabiospampinato** [comment]
@sergeevabc Can you open a separate issue about that, while filling the issue template? What happens on shortcuts depends on the state the app is in.

**Comment by sergeevabc** [comment]
Year passed, yet am still lost about intuitive notes navigation via keyboard.
Ctrl+E toggles editing of selected note, but what should I press next to get to another note?
