### ISSUE TITLE
Bug report template: Latest version

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#423]
Seems like a lot of people are still using outdated versions of Notable.
Should we include the latest version number in the bug report template?
And/or something like "Please test using the latest version to make sure your issue has not already been fixed"

**Comment by fabiospampinato** [comment]
No need, I think people will eventually close the app and an update check will be performed.

**Comment by fabiospampinato** [comment]
After that the app now checks more frequently for updates.
