### ISSUE TITLE
Autosuggest Tags

### ISSUE THREAD

**Issue by brycekunkel** [fabiospampinato/notable#424]
### Feature description

Would love to see the "Add Tags" input use an auto-suggest functionality based on the existing tags, again using a fuzzy search option. 

### Feature motivation

This would help with accidentally mistagging notes, as well as make the UX more enjoyable and a little easier.

**Comment by fabiospampinato** [comment]
Duplicate of #20.

**Comment by brycekunkel** [comment]
Sorry! Thanks for closing it out!
