### ISSUE TITLE
add building instructions

### ISSUE THREAD

**Issue by fosslinux** [fabiospampinato/notable#426]
### Feature description

Currently I cannot find any building instructions for an end user to create their own binary (I'm looking for Linux in particular).

### Feature motivation

I want to build for testing, but I cant find instructions on how to.

**Comment by RomanKornev** [comment]
Use `npm run build:linux` to build on Linux.
Use `npm run` to list all available scripts.

**Comment by fosslinux** [comment]
thanks! I'm not experienced with npm at all
