### ISSUE TITLE
Range selection via Shift+Click

### ISSUE THREAD

**Issue by kergoth** [fabiospampinato/notable#44]
Ctrl/cmd+click to individually pick notes works, but convention for multi-selection in other apps is to allow use of shift to select a range of them as well.

**Comment by beorn** [comment]
Additionally would be nice to be able to focus on the pane with the list of notes and use regular item list shortcuts, such as:

- cmd-a to select all notes
- shift-up/down to expand/shrink the selection of notes

**Comment by bendem** [comment]
Came here to say that. Literally the first thing I tried to do that didn't work:
I opened the app, imported from evernote, selected the tag `import-XXX` and wanted to remove it from all notes. I had to select each note individually, which was pretty annoying.

**Comment by fabiospampinato** [comment]
@bendem there's already a shortcut for selecting all notes, for your precise use case.

**Comment by bendem** [comment]
ah right, I tried cmd+a which didn't work, didn't realise there was another way.

**Comment by fabiospampinato** [comment]
@gamato `cmd+a` conflicts with the `cmd+a` for selecting all text. In order to keep them better separated I've changed the shortcuts for selecting all notes.

**Comment by gamato** [comment]
OK, I see. Normally, in native macOS apps, that's not a problem because it depends on the focus -- if I click on a note in the note list, then I can use cursor keys to move around and cmd-a to select all.

**Comment by fabiospampinato** [comment]
Implemented in https://github.com/fabiospampinato/notable/pull/61
