### ISSUE TITLE
Can't create/delete notebooks

### ISSUE THREAD

**Issue by johnletey** [fabiospampinato/notable#46]
I've noticed that there's no way to create/delete notebooks. If I'm missing something, please correct me, but I don't see any way to do this.

**Notes:** I'm on OSX 10.14 and running the application from the .app file, not from the terminal (this shouldn't make a difference though).

**Comment by johnletey** [comment]
Got it. Yes, not intuitive at all! Hopefully in the future there can be some buttons or drop down menu options for this, but for now, this will have to do. Anyways, thanks for the help!

**Comment by mhulse** [comment]
First thing I did was delete all the tutorial notebooks (I remember that being not intuitive). I then tried to create my own notebooks and realized that it was not obvious and gave up. Several weeks later I'm back and ran into same issue of "how to create a notebook". Found this issue. Thanks.

Could't you have some sort of menu option? Or, some sort of option in the "tags" dropdown for notebook? Maybe there is and I'm missing it?

Seems like having this be more intuitive would help with onboarding. 👍 

Thanks for the awesome app!

**Comment by fabiospampinato** [comment]
@mhulse It's probably a good idea to add some kind of context menu action for this. But it won't really just create a notebook, as notebooks without notes are meaningless as far as Notable is concerned, it will actually create a note inside that notebook. It may be a bit confusing but hopefully things will become clear the more the user uses the program.
