### ISSUE TITLE
Resizing sidebar doesn't work correctly after toggling Focus Mode

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#47]
Icon to resize sidebar only appears on the leftmost pixel of the window instead of the border between sidebars.
Also when I drag it to resize it resets to minimum width and I can only expand it but not contract.

Windows 10 1803 x64.

**Comment by fabiospampinato** [comment]
@RomanKornev good catch! I should re-initialize the resizing logic whenever focus mode is toggled.

**Comment by fabiospampinato** [comment]
Fixed, also now the proportions of the columns will be preserved.
