### ISSUE TITLE
Feature Request: Search inside notes rather than just on note titles

### ISSUE THREAD

**Issue by twwilliams** [fabiospampinato/notable#48]
I would love to be able to search for notes based on their content and not just their titles.

**Comment by millsoft** [comment]
just installed Notable, really cool app. But the search inside notes is the most used feature I use in Evernote. I could search in terminal using grep but it would be nice to be able to do this in Notable.

**Comment by corwinou** [comment]
I just discovered your app and indeed coming from Evernote. Looks amazing, but as a basic feature, I also think it really needs to search inside notes !

**Comment by openstep** [comment]
Hi,

Could you please highlight the search results on the notes so that it is possible to find the search results inside the notes.

Thanks

**Comment by fabiospampinato** [comment]
@openstep #243

**Comment by openstep** [comment]
So is that mean this idea will not be implemented or it will be?
"Feature Request: Search inside notes rather than just on note titles #48" closed
I do not get it.

**Comment by fabiospampinato** [comment]
> So is that mean this idea will not be implemented or it will be?

Most probably.

> I do not get it.

This is a duplicate issue, we are tracking what you requested in the issues I linked you.

**Comment by openstep** [comment]
Hi,

As an idea:
https://github.com/DevTomek-pl/Search-Text-Plugin-for-Notable
Could you build this in to your code? Than the issue is solved.

Br,
Csaba
