### ISSUE TITLE
Feature Request: Nice UI options for creating/deleting notebooks

### ISSUE THREAD

**Issue by johnletey** [fabiospampinato/notable#49]
As I've learned from #46, there is no intuitive way to create/delete notebooks. It would be extremely handy to have a more intuitive way to create/delete notebooks!

**Comment by fabiospampinato** [comment]
Notable is just a front-end for your notes, if there are no notes inside notebook A then there's no notebook A at all. IMHO treating notebooks as special tags is the right abstraction, rather than adding some other feature specific to notebooks I think this will be mostly solved by adding autocomplete support https://github.com/fabiospampinato/notable/issues/20

**Comment by MatanRubin** [comment]
I agree with @johnletey . I had to actually read the documentation to understand how to create a new notebook, and found the solution un-intuitive.
I think users should have an intuitive way for creating/deleting notebooks. From an implementation standpoint, a notebook should represent a directory in the data folder, so the "Create Notebook" button should just create an empty directory, and the "Delete Notebook" button should just delete a directory.

BTW, thanks for the awesome work. Notable still has a way to go, but it seems very promising!

**Comment by brpaz** [comment]
@fabiospampinato sorry to hijack this closed issue, but I had the same issue as many trying to understand how to create a notebook. If you dont see a Notebook as a folder, then why having notebooks at all? Why not having only tags? Honestly the way it is right now I cant see any utility for Notebooks.

**Comment by fabiospampinato** [comment]
@brpaz they help with notes organization, if you don't need notebooks you don't have to use them at all.

**Comment by tforward** [comment]
First, I really like what your doing with this project

> Moved From: #397 
> Added feature would be Right click on Notebooks >>> New Notebook >>> Prompt user for name

> This doesn't make sense in the context of Notable, as we have no concept of notebooks that don't > contain any notes. Read more about this here and here.

As other users have mentioned, I had to read, then re-read the documentation to figure out **how** to create a new notebook.

Can't you just flip the logic and just use the same functions that already exist in the program with no  fundamental shift in how the program works under the hood.? Just have it as a UI context menu

For example: 
As a user: Right click on Notebooks >>> New Notebook >>> Prompt user for name 

Program Logic:
Create Empty Note >>> Add tag "Notebooks/[USER_INPUT_VALUE]" >>> Goto / bring new note into context for user

Would be same for rename:

As a user: Right click on Notebooks >>> Rename >>> Prompt user for new name 

Program Logic: Selects all tags with the same Notebooks/[OLD_NAME] >>> Replace with "Notebooks/[USER_INPUT_VALUE]"

For the the users perspective, they would not know that it's doing the creation/renaming of the notebook in reverse order

**Comment by fabiospampinato** [comment]
> Can't you just flip the logic and just use the same functions that already exist in the program with no fundamental shift in how the program works under the hood.? Just have it as a UI context menu

We could do that, but I'm not sure if that solves the problem. In other note-taking apps they have empty notebooks, if we are going to implement this just for avoiding confusion I think it will also generate some more confusion as people aren't expecting a new note to be created when creating a notebook, and existing notebooks disappearing when all their notes have been deleted.

Maybe the tutorial notes about notebooks can be improved instead?

**Comment by MatanRubin** [comment]
How about ditching the Notebook concept altogether? What is the actual difference between a notebook and a tag?

**Comment by fabiospampinato** [comment]
@MatanRubin Other than the icon? Not much really. I like my notes better organized this way, you're free not to use notebooks at all of course.
