### ISSUE TITLE
Evernote import does not seem to work

### ISSUE THREAD

**Issue by artemave** [fabiospampinato/notable#50]
Hello!

I have years of evernote exported into a file:

![image](https://user-images.githubusercontent.com/23721/50488194-838fdf80-0a01-11e9-911c-90f2a255687e.png)

But when I import it into Notable nothing happens. Are there any logs? Or perhaps there is a shortcut to peek into the dev tools?

Thanks,
Artem

**Comment by fabiospampinato** [comment]
How many notes are in there? Thousands?

My guess it that the program takes too long to complete the action and it looks like it froze.

For now you either have to just wait or you can use [enex-dump](https://github.com/fabiospampinato/enex-dump) directly using your data directory as the destination path and then once the operation is completed re-open Notable.

In the future the import logic should run off the main thread, possibly showing a progress bar as well.

**Comment by artemave** [comment]
There are 440 notes.

Notable does not appear frozen at all. Neither there is any spike in cpu when I import that file. It really looks like nothing is happening.

I'll try enex-dump - thanks for the tip!

**Comment by fabiospampinato** [comment]
> Notable does not appear frozen at all. 

Can you actually change the currently active note while importing the file? If you can and notes aren't imported I guess there's a bug somewhere 🤔

**Comment by gaui** [comment]
Same here. Doesn't work importing in Notable, nor does enex-dump work.

```
gaui@GAUIPC MINGW64 ~/Desktop/evernote/enex
$ enex-dump --src ./Almennt.enex

Cannot read property 'split' of undefined

gaui@GAUIPC MINGW64 ~/Desktop/evernote/enex
$ enex-dump --src ./Gaui.enex

Cannot read property 'file-name' of undefined

gaui@GAUIPC MINGW64 ~/Desktop/evernote/enex
```

Would be better if you would display raw error and stacktrace, so it would be possible to fix the code.

**Comment by fabiospampinato** [comment]
@gaui good idea, thanks. Would you be able to share with me the troublesome `.enex` file so that I can reproduce this?

**Comment by TheConnMan** [comment]
I found that some of my notes with attachments failed to import. A bulk import didn't work (no freezing, just nothing happening), so I did smaller batches. Some notes with attachments worked, some didn't. I couldn't find any pattern. Maybe those which had been shared had issues?

**Comment by fabiospampinato** [comment]
@TheConnMan I'm not sure, if you can send an `.enex` file that reproduces the problem I can get this fixed.

**Comment by gaui** [comment]
@fabiospampinato Here you go: https://www.dropbox.com/s/jowvijlkk5ysric/TestStack.enex?dl=1

**Comment by fabiospampinato** [comment]
Multiple problems have been resolved in the last `enex-dump` release, you guys might not have experienced the same one though, I'm closing this as the `.enex` @gaui attached is now parsed properly, if you guys find any other problem feel free to open another issue, either here or in [`enex-dump`](https://github.com/fabiospampinato/enex-dump) directly.
