### ISSUE TITLE
Feature request: support checkbox syntax

### ISSUE THREAD

**Issue by mikehearn** [fabiospampinato/notable#51]
GitHub lets you make tick boxes:

- [ ] like
- [ ] this

But this syntax doesn't seem to work in Notable. It'd be great if it did.

**Comment by fabiospampinato** [comment]
Yes it's a bug, it's actually supposed to be well supported since you should be able to create/check checkbox via `cmd/ctrl+enter` and `alt+d`.

Duplicate of #19
