### ISSUE TITLE
Recommended / Suggested mobile markdown editor which work well together

### ISSUE THREAD

**Issue by WilliamTheMarsman** [fabiospampinato/notable#55]
Is there a mobile markdown editor you feel works well for working with the format of Notable?

**Comment by johnletey** [comment]
I've heard of [Ulysses](http://www.ulyssesapp.com/), which is an extremely UI friendly app that you can edit markdown in on your phone. What you need to do, is to put your Notable data directory into Google Drive/Dropbox/iCloud Drive and then open that folder in the Ulysses app on your phone.

**Comment by WilliamTheMarsman** [comment]
thanks
