### ISSUE TITLE
WikiLink syntax support

### ISSUE THREAD

**Issue by lukaskawerau** [fabiospampinato/notable#56]
Would it be possible to add WikiLink support (i.e.`[[Description|Link to Note]]`) to Notable?  
Here's a great essay on why it's a great feature, would love it if you could add this:
https://medium.com/@timkingwriter/welcome-to-the-note-taking-apocalypse-64a74481a5ab

**Comment by schmeisers** [comment]
Yes, this would be a great feature.  The "folder of markdown files" audience probably already has a lot of notes with this link syntax from Vimwiki and Org-mode.  It would lower the cost of switching if `notable` were compatible with these other workflows.

**Comment by fabiospampinato** [comment]
I don't see this happening. The current solution is better IMHO, we can distinguish between notes, attachments and tags, and with the current solution you can also embed attachments inline, I don't see this things possible with WikiLink, but even if they are possible I would rather not support 2 different syntaxes for doing the same thing.

**Comment by lukaskawerau** [comment]
I'm very sad to hear that 😢
Notable is _literally_ the note taking app I've been looking for forever, except for this one missing feature. Wiki-style links are critical to a fluent writing workflow, and I'm not sure I understand why it would be bad to add that behavior for linking to notes. I think linking to attachments and tags doesn't need to be solved with this, but Wiki-style links are just the best way to link to other notes/pages.  

I would really love to switch to Notable, but I can't see me switch literally thousands of notes over to a syntax that is specific to notable when many other projects support it (even though they are missing other features).

**Comment by lukaskawerau** [comment]
There is also an implementation in the [mume](https://github.com/shd101wyy/mume) package that maybe makes it easy enough to support it without too much overhead :)
Direkt link to the file: https://github.com/shd101wyy/mume/blob/master/src/custom-markdown-it-features/wikilink.ts

I would really love this feature in Notable, if there's anything I can do to help let me know.

**Comment by fabiospampinato** [comment]
On a second thought maybe it's ok to support this just for linking to other notes. 

It would require making a Markdown extension for this, analogous to [this one](https://github.com/fabiospampinato/notable/blob/master/src/renderer/utils/markdown.ts/#L74). The only problem is the extension of the note, in the current format we require people to use the full file name of a note: `[foo](@note/My Other Note.md)`, my understanding is that WikiLinks perhaps refer to the title instead?

I guess we should:

- Use the provided extension, if any
- Default to `.md` if none is provided
- Or maybe "search" for a note with that title

If anyone would like to take a shot at this I'll be happy to consider a PR for this.

**Comment by lukaskawerau** [comment]
Yes, this is such great news, thank you!

**Comment by mnikn** [comment]
seems like a great feature, but in my sight the wikiLink usually shows the general introduction, maybe it would be too large if we show all content of the note in popup, or you have any idea for it? @lukaskawerau

**Comment by lukaskawerau** [comment]
@mnikn For me the point in adding support for this is not in enabling preview through a popup, but ease of writing. It is much faster to write `[[Description|Note Title]]` than anything else, and it doesn't implement special, notable-specific syntax. If we then had a preview-popup that would certainly be nice, but the main advantage would be the linking and maybe autocomplete functionality.  
@fabiospampinato In my personal use the link refers to the filename as well, so the behaviour would be analogous to the existing behaviour.  
I do agree that using a provided extension if it exists and defaulting to `.md` otherwise is the best way to go.

**Comment by matejdro** [comment]
What if you would just parse markdown URLs that do not contain http(s) as note links by default? That way you can just type `[Description](Note Title)` which is about as fast as your example above.

**Comment by fabiospampinato** [comment]
@matejdro that's confusing as it would conflict with the normal way of defining urls, I don't know why somebody would want to make a link pointing to "Note Title" in a Markdown file but you can if you want.

**Comment by lukaskawerau** [comment]
I think it's important to keep liking behaviour as interchangeable as possible, where possible. WikiLink `[[`-Syntax is an established way of linking text documents. @fabiospampinato's `[](@note/...)` is a really great way to transfer Markdown syntax to linking local textfiles, so I don't think we would need to change this in the way you propose, @matejdro.  
The reason I'm advocating for `[[`-Syntax is that 

1. it's an established way of linking to documents in the same tree
2. it's (imo) even faster to type than standard markdown syntax
3. it's clearly distinguishing between local links and outbound/web links
4. it's not specific to Notable, i.e. other apps exist that use it (I'm currently using it with a gollum git-based wiki), and is therefore more portable than `[Note](@note/...)` syntax

**Comment by fabiospampinato** [comment]
> it's an established way of linking to documents in the same tree

Maybe in the Wiki ecosystem, I personally have never seen it used anywhere else.

> it's (imo) even faster to type than standard markdown syntax

This for the most part doesn't matter, especially when autocomplete #20 gets implemented. Also if you write our special syntax as `[](@notes/foo)` you don't even have to type the title, so I'm not sure WikiLink is faster.

> it's clearly distinguishing between local links and outbound/web links

The current solution is clear enough in this regard IMHO.

> it's not specific to Notable, i.e. other apps exist that use it (I'm currently using it with a gollum git-based wiki), and is therefore more portable than [Note](@note/...) syntax

Sure, that's what made me reconsider my previous decision, but I think you can switch between the 2 syntaxes with a single search & replace so I wouldn't consider this a hugely important reason.

**Comment by lukaskawerau** [comment]
> > it's an established way of linking to documents in the same tree
> 
> Maybe in the Wiki ecosystem, I personally have never seen it used anywhere else.

- [nvAlt uses it since 2012 ](http://brettterpstra.com/2012/09/28/external-linking-for-nvalt-notes-part-1/)
- [Dan Sheffler uses it with SublimeText](http://dansheffler.com/blog/2015-08-03-sublime-syntax-definition/)
- the mentioned [Gollum](https://github.com/gollum/gollum/wiki)
- 1Writer [recently added support](http://1writerapp.com/)
- [Zettelkasten](https://zettelkasten.de/)

To just name the ones I can remember immediately. I think the "market" for this is quite big, so I'm very happy that Notable will get this feature as well :)

> > it's not specific to Notable, i.e. other apps exist that use it (I'm currently using it with a gollum git-based wiki), and is therefore more portable than [Note](@note/...) syntax
> 
> Sure, that's what made me reconsider my previous decision, but I think you can switch between the 2 syntaxes with a single search & replace so I wouldn't consider this a hugely important reason.

If I want to go Notable only, sure. But as the list of apps above shows I might want to use other apps concurrently that do not allow me to use Notable's syntax.

**Comment by fabiospampinato** [comment]
> If I want to go Notable only, sure. But as the list of apps above shows I might want to use other apps concurrently that do not allow me to use Notable's syntax.

Good point 🤔 

Thanks for the list of apps that use WikiLinks too, I wasn't aware of that.

**Comment by lukaskawerau** [comment]
Hey @fabiospampinato I've gone ahead and tried to write a Markdown extension for this like the ones for Notes.  
But since I've never written JavaScript let alone worked in Electron or TypeScript I can't seem to figure out how to make this actually work in the app. But maybe my code can provide someone some inspiration to make this into a proper pull-request.  
So, here's the code:  


```{javascript}
    // Wikilink
    wikilink () {

      const {path: notesPath} = Config.notes;

      if ( !notesPath ) return [];

      return [
        { // Link Button
          type: 'output',
          regex: `\[\[(.*?\|?.*?)\]\]`,
          replace ( match, $1 ) {
            const content  = $1
            const splits = content.split("|"); 

            if (splits.length === 1) {
              const wikiLink = splits[0].trim();
              const linkText = splits[0].trim();
            }
            else {
              const wikiLink = splits[1].trim();
              const linkText = splits[0].trim();
            }

            wikiLink = decodeURI ( wikiLink );
            const basename = path.basename ( wikiLink );
            const filePath = path.join ( notesPath, wikiLink, '.md' ); // the extension should be configurable (= default extension)
            return `<a target="_blank" href="file://${filePath}" class="note button gray" data-filepath="${filePath}"><i class="icon small">note</i><span>${linkText}</span></a>`;
          }
        },
        { // Link
          type: 'output',
          regex: `\[{2}(.*?\|?.*?)\]{2}`,
          replace ( match, $1 ) {
            const content = $1
            const splits = content.split("|"); 

            if (splits.length === 1) {
              const wikiLink = splits[0].trim();
              const linkText = splits[0].trim();
            }
            else {
              const wikiLink = splits[1].trim();
              const linkText = splits[0].trim();
            }

            wikiLink = decodeURI ( wikiLink );
            const filePath = path.join ( notesPath, wikiLink, '.md' ); // the extension should be configurable (= default extension)
            return `<a target="_blank" href="file://${filePath}" class="note" data-filepath="${filePath}"><i class="icon xsmall">note</i>${linkText}</a>`;
          }
        }
      ];

    },
```

Again, this is probably super embarassing code since I don't understand JS at all, so this is just me kinda pseudo-coding based on what's in the source code and how I *think* things should work (Case in point: I tried two different regexes (both of which should work) because I thought that might be the issue why it's not working). But again, maybe it can serve as a starting point for someone else to implement this.

**Comment by lukaskawerau** [comment]
@fabiospampinato is there anything else I can do to make this happen? Do I need to register this extension somewhere else except the file itself?

**Comment by fabiospampinato** [comment]
@lukaskawerau active extensions are defined here:

https://github.com/fabiospampinato/notable/blob/508bdd1623f2c4646d4c90614fa690a1f4baf335/src/renderer/utils/markdown.ts#L236-L241

I haven't worked yet on this because I think there are more pressing issues to solve first, but mainly the biggest roadblock here is detecting when `[[Foo|bar]]` is in a code block, in which case it shouldn't get transformed into an anchor link. I'm not quite sure how to do that.

**Comment by fabiospampinato** [comment]
> but mainly the biggest roadblock here is detecting when [[Foo|bar]] is in a code block

Which is not too big of an issue though, we could fix this later on.

**Comment by lukaskawerau** [comment]
Thank you for showing me how to register the extension, now things are actually happening when I edit the code!  
The biggest problem I'm having right now is that the regex is not matching things even though it should (other expressions work). As a minimal example:

If you have a string `thisismysupertest` in a document, this works:
```
    // Wikilink
    wikilink () {

      const {path: notesPath} = Config.notes;

      if ( !notesPath ) return [];

      return [
        { // Link Button
          type: 'output',
          regex: `(thisismysupertest)`,
          replace ( match ) {
            return `lookatthismatch`;
          }
        }
      ];

    }
```
But if you have a string `[[Link to Note]]` in your document, this doesn't

```
    // Wikilink
    wikilink () {

      const {path: notesPath} = Config.notes;

      if ( !notesPath ) return [];

      return [
        { // Link Button
          type: 'output',
          regex: `\[{2}(.*?\|?.*?)\]{2}`,
          replace ( match ) {
            return `lookatthismatch`;
          }
        }
      ];

    }
```

even though `\[{2}(.*?\|?.*?)\]{2}` is definitely the right expression to match the string, as you can see here:  
https://regex101.com/r/egme08/1

**Comment by fabiospampinato** [comment]
> even though `\[{2}(.*?\|?.*?)\]{2}` is definitely the right expression to match the string, as you can see here:

Well, actually you are defining a string, which showdown will in turn transform to a regex, maybe something it's quite working there. You can also define a plain regex though.

Also you're defining your extensions as "output" extensions:

>          type: 'output',

So they manipulate the generated html rather than the source markdown, you can try using `language` instead o `output`.

**Comment by lukaskawerau** [comment]
Ha, with a plain regex it works!  
PR incoming.  
Code blocks still need fixing, though, you are right about that.

**Comment by lukaskawerau** [comment]
Added a first commit in #356.  
Regarding the code block issue: is it possible to check where in the DOM a regex match occured? If we can do that, it would be possible to see if the match is inside a `<code>` block.

**Comment by fabiospampinato** [comment]
> it possible to check where in the DOM a regex match occured?

Not really, extensions are dealing with a string, not a DOM object. We could parse the string into a DOM object but that would be too expensive.

**Comment by lukaskawerau** [comment]
Aaand that's also a non-issue, fixed.

Wikilinks are now not created when inside code blocks or spans.

**Comment by fabiospampinato** [comment]
Closing as it's implemented in v1.3.0.

**Comment by muescha** [comment]
i understand right that after finishing #20  you also include the standard markup link like `[text](title)`?

**Comment by fabiospampinato** [comment]
@muescha what do you mean? Are you asking what links syntaxes the autocomplete will support? 🤔

**Comment by muescha** [comment]
in addition to the wiki style syntax `[[new link|05 - Notes]]` (since v1.3.0) i should able to write also the "standard" markup link syntax: `[new link](05 - Notes)`

**Comment by fabiospampinato** [comment]
@muescha You can already to that, it works like this: `[new link](@note/05 - Notes.md)`. You can't omit the `@note` token because these kinds of links could also link to attachments for instance, we need a way to distinguish between those.

**Comment by muescha** [comment]
thx!

**Comment by qb42** [comment]
I guess my search for the reason why Notable does wikilinks backwards is over.

FYI, it's [[Actual Title|what gets displayed]] not [[what gets displayed|Actual Title]].
https://en.wikipedia.org/wiki/H:WIKILINK
