### ISSUE TITLE
Error Running Dev on Linux

### ISSUE THREAD

**Issue by TheConnMan** [fabiospampinato/notable#6]
I'm running into the following error after a fresh install on Ubuntu after running `npm run dev`:

```
ERROR in ./src/renderer/render.tsx
Module not found: Error: Can't resolve '@static/css/notable.min.css' in '/path/to/notable/src/renderer'
  @ ./src/renderer/render.tsx 37:0-37
  @ ./src/renderer/index.ts
  @ multi ./src/renderer/index.ts

ERROR in ./src/renderer/render.tsx
Module not found: Error: Can't resolve '@static/javascript/notable.min.js' in '/path/to/notable/src/renderer'
  @ ./src/renderer/render.tsx 38:0-43
  @ ./src/renderer/index.ts
  @ multi ./src/renderer/index.ts
```

Any help would be appreciated, even if the answer is just you don't do dev on Linux. Thanks.

**Comment by fabiospampinato** [comment]
It seems you forgot to run `npm run svelto:dev` first, which generates those files. Read [here](https://github.com/fabiospampinato/notable#contributing).

**Comment by gunt3001** [comment]
I'm getting the same errors. Running `npm run svelto:dev` or `npm run svelto:prod` doesn't seem to generate any files on my machine.

**Comment by dps** [comment]
I am also seeing the same error on MacOS X 10.14 having run `npm run svelto:dev`, its output was simply:
```
$ npm run svelto:dev

> notable@1.0.0 svelto:dev /Users/dps/notable
> svelto build --env development

```

**Comment by RomanKornev** [comment]
Running `npm run svelto:dev` produces `The system cannot find the path specified.` on Windows 10 x64 1803.

**Comment by TheConnMan** [comment]
I ran all the commands in the readme just in case this was necessary. I still got the same errors.

**Comment by dps** [comment]
If you also run `npm install pacco` it seems to work

**Comment by RomanKornev** [comment]
If anyone still has issues compiling:
`Failed to load "notable\eyJicm93c2VycyI6WyJpZSA..."` - just re-clone the repository again.

**Comment by jcuenod** [comment]
Shouldn't `pacco` be in `package.json`?

**Comment by fabiospampinato** [comment]
@jcuenod it's required by Svelto, which is `package.json`, and does define `pacco` in its `package.json`.

**Comment by jcuenod** [comment]
Hmm, well `pacco` didn't install when I ran `npm install` after pulling the latest. However, I can get notable running now (errors are still occurring though).

**Comment by fabiospampinato** [comment]
@jcuenod can you reproduce if you run `npm i` in a freshly cloned repo?

**Comment by jcuenod** [comment]
Nope, I'm having success now.
Thanks
