### ISSUE TITLE
Imported notes on Windows show carriage return character "CR"

### ISSUE THREAD

**Issue by alecgeatches** [fabiospampinato/notable#66]
When importing `.md` files in native Windows format, the editor shows "CR" on each newline:

![notable-crs](https://user-images.githubusercontent.com/17870752/50501130-d8c70200-0a90-11e9-883d-25abe0bbe6a3.PNG)

The markdown preview still works well, but it'd be nice if these were automatically converted on import.

**Comment by fabiospampinato** [comment]
Could you post a note that reproduces the problem?

**Comment by alecgeatches** [comment]
Sure. I opened the "Welcome to Notable" note in an external editor and saved with CRLF endings. Save this file and rename with `.md` extension and import: [Welcome to Notable.txt](https://github.com/fabiospampinato/notable/files/2713897/Welcome.to.Notable.txt). It should reproduce the problem.

**Comment by alecgeatches** [comment]
I think it might be from the codemirror options here: https://github.com/fabiospampinato/notable/blob/e0d27304447a57da4dc3c72926c173ee7e968369/src/renderer/components/main/mainbar/code/index.tsx#L22

The [code mirror documentation](https://codemirror.net/doc/manual.html) says the default value will handle `LF`/`CRLF`:

> `lineSeparator`: `string|null`
> Explicitly set the line separator for the editor. By default (value `null`), the document will be split on CRLFs as well as lone CRs and LFs, and a single LF will be used as line separator in all output (such as `getValue`). When a specific string is given, lines will only be split on that string, and output will, by default, use that same separator.

Changing that might do the trick, assuming you don't need it set for another purpose.

**Comment by fabiospampinato** [comment]
@alecgeatches thanks for looking into this! Fix coming with the next release.
