### ISSUE TITLE
Can't add tag: Tag is duplicate

### ISSUE THREAD

**Issue by eitch** [fabiospampinato/notable#72]
I just installed Notable and copy pasted all my notes from SimpleNote, which i was using previously and am now busy adding some tags. After a few tags Notable says i can't add a tag, because it is a duplicate. I think it somehow still thinks i'm adding the tag to a previous note.

When i switch notes and open the tag menu, then it shows what i previously typed, but the tag was not created because of the duplicate error message.

**Comment by fabiospampinato** [comment]
Sounds like a bug, could you try to craft some steps that will be able to reproduce the issue?

**Comment by eitch** [comment]
Here is a simple way how i managed to reproduce it.

[notable_duplicate_tag.zip](https://github.com/fabiospampinato/notable/files/2716589/notable_duplicate_tag.zip)

**Comment by fabiospampinato** [comment]
Thanks for the screencast, was very useful.

**Comment by polizz** [comment]
Definitely appears to be reproducible if you leave the previous tag "widget" open, then navigate to a new note and try to reuse that same tag widget.
