### ISSUE TITLE
cyrilic problem

### ISSUE THREAD

**Issue by higowas** [fabiospampinato/notable#73]
title not displayed if the title is written in cyrillic (ukraine)
![screen](https://i.imgur.com/KCxrRFS.png)

**Comment by kolarski** [comment]
I think I narrowed down the issue: 

```javascript
getFirstUnemptyLine ( str: string ): string | null {
    const match = str.match ( /^.*?\w.*$/m );
    return match && match[0];
}
```
The regex and in particular - `\w` is not unicode friendly - it matches only latin chars.
Should be replaced with something like `[\wа-я]` to include cyrillic chars.
