### ISSUE TITLE
Feature Request: Show all notes when selecting Notebook/Tag

### ISSUE THREAD

**Issue by dschuessler** [fabiospampinato/notable#75]
When a notebook or tag is selected, the note view currently shows the uppermost note.

Feature request: Instead of showing the uppermost note only, show all notes of this notebook / tag one below the other so users can scroll through their content.

**Comment by fabiospampinato** [comment]
Sorry this wouldn't be good for performance nor I think is a necessary feature. Perhaps we could add a richer note preview into the middlebar, but that's a separate issue.
