### ISSUE TITLE
Split-view editing/previewing

### ISSUE THREAD

**Issue by JeremyLG** [fabiospampinato/notable#77]
Hello,

Is there way to have like in Atom, a live preview rendering option ?

When you toggle the editing and start modifying the note, you would see on the right side what it would look like as a preview.
Like you don't need the full screen to edit the note so we would split the screen to make a left side to edit and a right side to preview it (live as-you-type)

**Comment by fabiospampinato** [comment]
Not currently, but It's something I'd like to support as well.

**Comment by JeremyLG** [comment]
Waouw that was fast, GG
