### ISSUE TITLE
title doesn't support other languages except English

### ISSUE THREAD

**Issue by kele1997** [fabiospampinato/notable#78]
Hi,
I am a Chinese user of this software,I find that the title must begin with ascii words or numbers.If I use Chinese characters like "测试",there will be a "Untitled" in the sidebar.I think maybe this also happens on other kind of languages.
thanks.
![](https://i.loli.net/2018/12/28/5c262fb61795a.png)

**Comment by kolarski** [comment]
https://github.com/fabiospampinato/notable/issues/73
