### ISSUE TITLE
Feature Request: Export notes to PDF

### ISSUE THREAD

**Issue by veselfil** [fabiospampinato/notable#79]
It would be nice if it was possible to export a note as a PDF. I would like to share my notes with people who have no idea what markdown is, and a PDF would in my opinion be the best file format for such purposes.

If this is a feature you'd like to have in the app, I could implement it.

**Comment by Philiphlop** [comment]
If sharing with the intention of letting people edit, then more than PDF would be required. Such as TXT (trivial I know), ODT, RTF. There are tools that can convert many to many, such as Pandoc.

**Comment by fabiospampinato** [comment]
> If this is a feature you'd like to have in the app, I could implement it.

I think we should have a couple of `Export -> Markdown, PDF` menu entries at least, feel free to submit a PR for this.

**Comment by fabiospampinato** [comment]
I'm closing this in favor of #14, which is more generic.
