### ISSUE TITLE
Feature Request: Google Drive support

### ISSUE THREAD

**Issue by danieldaeschle** [fabiospampinato/notable#81]

**Comment by danieldaeschle** [comment]
If i don't have a google drive client on my pc inszalled?

Philip Whiteside <notifications@github.com> schrieb am Fr. 28. Dez. 2018 um
16:25:

**Comment by fabiospampinato** [comment]
> If i don't have a google drive client on my pc inszalled?

Then that's not supported, I don't plan to support this either, probably in the future there will be an "official" webapp or something.

**Comment by dps** [comment]
Just FYI, Fabio. I know you don't intend to support this in the main branch and that's cool - it's a smart choice to keep things simple, I have a still hacky but functional Google Drive sync working in this PR in a fork (that fork is also adding some other stuff I don't think you'd want in the mainline, like an omnibox)

Just wanted you to know - no reply expected!

https://github.com/dps/notable/commit/9e77f849034fc53a22ce46d2fbcb8b23cb2d69d3
