### ISSUE TITLE
Feature Request: WebDAV support

### ISSUE THREAD

**Issue by danieldaeschle** [fabiospampinato/notable#82]

**Comment by fabiospampinato** [comment]
This seems out of scope? But I'm not very familiar with WebDAV.

**Comment by danieldaeschle** [comment]
It would support nextcloud and owncloud as storage.

Fabio Spampinato <notifications@github.com> schrieb am Fr. 28. Dez. 2018 um
17:03:

**Comment by fabiospampinato** [comment]
I don't think there's any plan to support other storage options nativelly other then when I'll make a web app out of this.
