### ISSUE TITLE
Synchronization between computers/other devices?

### ISSUE THREAD

**Issue by spiral6** [fabiospampinato/notable#9]
More like a long term milestone, but creating a server/client or even just opening notebooks via Google Drive or some other cloud storage?

**Comment by fabiospampinato** [comment]
You can already put the data directory inside Google Drive and achieve synchronization this way.

A server could be another solution, that may also enable mobile apps, that's definitely long term.

**Comment by fabiospampinato** [comment]
I'm closing this in favor of the current way of doing this (Dropbox/Git) and the future issues that will tackle this: #83 and #23.
